### ISSUE TITLE
[Bug]: When selecting minimized window on other desktop in Latte Dock, GUI freezes

### ISSUE THREAD

**Issue by jonathansharpe** [Bismuth-Forge/bismuth#109]
### Summary

Selecting a minimized window in Latte Dock on another desktop causes everything to freeze, requiring a restart (to my knowledge).

### Steps to Reproduce

1. Open a program on two separate desktops
2. Minimize program on desktop 1
3. Switch to desktop 2
4. Using Latte Dock, select the minimized program on desktop one
5. Everything freezes

### Expected behavior

For the window to be selected and be tiled alongside the existing window(s) on the other desktop.

### Bismuth version

1.01

### KDE Plasma version

5.22.5

### The platform KWin is running on

X11

**Comment by jonathansharpe** [comment]
Ok upon further testing, this is correct. Disabling the Monocle layout does prevent freezing under the conditions I listed. However, it still freezes under these conditions, which I forgot to list in the original bug report.

1. Open up windows A and B on desktop 1, window C on desktop 2
2. Minimize window A but not window B
3. Switch to desktop 2
4. Click on window A in Latte Dock
5. Everything freezes

This is reproducible even with the Monocle layout unselected.

**Comment by KristianUSN** [comment]
I'm not sure if this is related but it kinda seems to be, but whenever I try to edit a Latte dock/panel everything freezes up. I thought it was an issue with Latte for a while but it stops happening if I disable Bismuth.

**Comment by ParanoidNemo** [comment]
Here to report the same issue, basically if Bismuth is active, is not possible to modify settings for Latte dock/panel, everything freezes and you have to reboot.

**Comment by gikari** [comment]
You have to `git checkout` this PRs, install it using [these instructions](https://github.com/gikari/bismuth#from-source) and restart KWin if you're on X11 with:
```bash
kwin_x11 --replace & disown
```
