### ISSUE TITLE
[FEATURE]: Provide an Icon for Bismuth OSDs

### ISSUE THREAD

**Issue by gikari** [Bismuth-Forge/bismuth#129]
### Summary

All Plasma OSDs have an icon to represent what the Popup is talking about: brightness, keyboard, audio.

Some examples:

- Brightness
![Screenshot_20211022_223139](https://user-images.githubusercontent.com/14205339/138512654-d8ffebcf-c6cd-49b7-a7ad-87a68b11c865.png)

- Audio
![Screenshot_20211022_223158](https://user-images.githubusercontent.com/14205339/138512682-861d0788-43a2-4064-a357-a0fd63352902.png)

However, the current Bismuth OSD does not have an icon:
![Screenshot_20211022_223406](https://user-images.githubusercontent.com/14205339/138512916-bfe9484d-73f2-4ceb-a04f-7e78a0a21d28.png)

This makes a little of a confusion about whom the popup belongs to and also hurts consitency.

### A clear and concise description of what you want to happen

Bismuth should have an icon with the same style as in the examples above to indicate the ownership of the popup. Preferably, this should be a generic icon (i.e. not a Bismuth logo), similar maybe to TMux logo (tiled windows' contours):
![image](https://user-images.githubusercontent.com/14205339/138513309-34a95be0-f985-4508-8e29-5fe034389426.png)

**Comment by verahawk** [comment]
So I ~stole~ slightly modified the [preferences-system-windows-effect-presentwindows](https://github.com/KDE/breeze-icons/blob/master/icons/applets/64/preferences-system-windows-effect-presentwindows.svg) icon from the Breeze theme:

![bismuth-osd](https://user-images.githubusercontent.com/28950897/140198695-b085cd86-b441-4718-a1ac-4ada1bce2920.png)
And this is how it looks like in the OSD popup:

![preview](https://user-images.githubusercontent.com/28950897/140198919-14b41f8c-8f66-4423-9c2f-ece54c4f9b80.jpg)

Let me know if you like it (if not, that's fine, hopefully someone else will create something better suited).

**Comment by gikari** [comment]
> So I ~stole~ slightly modified the [preferences-system-windows-effect-presentwindows](https://github.com/KDE/breeze-icons/blob/master/icons/applets/64/preferences-system-windows-effect-presentwindows.svg) icon from the Breeze theme:
> 
> ![bismuth-osd](https://user-images.githubusercontent.com/28950897/140198695-b085cd86-b441-4718-a1ac-4ada1bce2920.png)
> And this is how it looks like in the OSD popup:
> 
> ![preview](https://user-images.githubusercontent.com/28950897/140198919-14b41f8c-8f66-4423-9c2f-ece54c4f9b80.jpg)
> 
> Let me know if you like it (if not, that's fine, hopefully someone else will create something better suited).

Looks nice. What I would change, is that the icon should be monochrome. Currently the title bars in your icons are not monochrome.

**Comment by verahawk** [comment]
> Looks nice. What I would change, is that the icon should be monochrome. Currently the title bars in your icons are not monochrome.

Do you mean just removing the color separators?
![sc-apps-bismuth-osd_no-separators](https://user-images.githubusercontent.com/28950897/140303140-7677bc5d-c7ab-4c86-9fa4-30c2dda1073d.png)

Or making the title bars completely black as well?
![sc-apps-bismuth-osd_bw](https://user-images.githubusercontent.com/28950897/140304078-130edce0-68d1-4970-83b6-cabcae060999.png)

**Comment by gikari** [comment]
> > Looks nice. What I would change, is that the icon should be monochrome. Currently the title bars in your icons are not monochrome.
> 
> Do you mean just removing the color separators?
> ![sc-apps-bismuth-osd_no-separators](https://user-images.githubusercontent.com/28950897/140303140-7677bc5d-c7ab-4c86-9fa4-30c2dda1073d.png)
> 
> Or making the title bars completely black as well?
> ![sc-apps-bismuth-osd_bw](https://user-images.githubusercontent.com/28950897/140304078-130edce0-68d1-4970-83b6-cabcae060999.png)
> 

Both. Look at the examples in the begging - sound and brightness applets. Their icons are using one color, but with different shade. These are recolored icons. You may want to look at their SVG source

**Comment by verahawk** [comment]
![sc-apps-bismuth-osd](https://user-images.githubusercontent.com/28950897/140424215-33e2fa6a-ab4a-44d0-b9ca-deef2641e00a.png)

#eff0f1
---
![sample2](https://user-images.githubusercontent.com/28950897/140424222-d91f9986-bf20-444d-a15a-8c6ad190c087.png)

#232629
---
![sample1](https://user-images.githubusercontent.com/28950897/140424220-aaf9a991-d0ac-47bb-ab6f-1850edf8841e.png)
