### ISSUE TITLE
[FEATURE]: Option to Disable Floating Windows

### ISSUE THREAD

**Issue by MaybeAnonymous** [Bismuth-Forge/bismuth#145]
### Summary

A way to _disable floating windows,_ and make it impossible for them float above one another.

### A clear and concise description of what you want to happen

When I drag a window, I'd like it to _snap to the layout,_ instead of floating.

### A clear and concise description of any alternative solutions or features you've considered.

I used _Bismuth + Quarter Tiling_, **though** it is not the best solution. It may cause some bugs here and there.

### Additional info

I am running **KDE Plasma 5.23.2** on **ArcoLinux 64x.**

**Comment by gikari** [comment]
Not sure I understand. Do you want to drag a window into layout and make it attach to it?

**Comment by MaybeAnonymous** [comment]
> Not sure I understand. Do you want to drag a window into layout and make it attach to it? 

exactly
