### ISSUE TITLE
[Bug]: Compiling Error(fixed but ended up in another problem)

### ISSUE THREAD

**Issue by MaybeAnonymous** [Bismuth-Forge/bismuth#151]
### Summary

I get this error when trying to compile Bismuth:
```
CMake Error at CMakeLists.txt:11 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 5.80.0) with any of the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.
```

### Steps to Reproduce

download source code, extract
go into the source code folder
run:
```
npm install # Installs dependencies for building
npm run sysdep-install # Install system dependencies for building
npm run bi-install # Installs all Bismuth components

```
get this error when finishing compiling:
```
CMake Error at CMakeLists.txt:11 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 5.80.0) with any of the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.
```

### Expected behavior

To not get an error and for everything to compile and work

### Screenshots

![image](https://user-images.githubusercontent.com/89218161/140242039-5dcabf27-7f4a-4d0e-ab9b-c0f714f37f85.png)

### Bismuth version

2.0.0

### KDE Plasma version

5.23.2

### The platform KWin is running on

X11

### Additional context

I'm using Arco Linux 64x

**Comment by MaybeAnonymous** [comment]
Seems like there is an AUR package for that, installed it but did not work properly and now cannot remove. Where do I get help for this now

**Comment by MaybeAnonymous** [comment]
brb

**Comment by MaybeAnonymous** [comment]
update: i ran `yay -Sc` did not fix but seems to have removed some useless files

**Comment by MaybeAnonymous** [comment]
> update: i ran `yay -Sc` did not fix but seems to have removed some useless files

i again did `yay -S bismuth` seems like it re-installed bismuth properly, yet i still cannot figure out how to remove, i can keep it though since it is no longer broken

**Comment by gikari** [comment]
> > update: i ran `yay -Sc` did not fix but seems to have removed some useless files
> 
> i again did `yay -S bismuth` seems like it re-installed bismuth properly, yet i still cannot figure out how to remove, i can keep it though since it is no longer broken

For anything AUR package related, you should ask a maintainer of the package.

The error you've got was indicating, that you didn't have extra-cmake-modules installed. It should have it installed via pacman and sysdep-install.sh script.
