### ISSUE TITLE
[DEV]: Make life easier for packagers

### ISSUE THREAD

**Issue by gikari** [Bismuth-Forge/bismuth#152]
### Summary

This is an issue, where the packagers could express their needs for creating packages and also notifying about ready to use repos/packages, so it can be linked in the readme.

For example, in the recent r/kde post there was a note about distros not liking using NPM in the packaging. It was suggested to provide an already compiled JavaScript folder, so that using NPM wouldn't be necessary.

### Additional info

The issue will be closed, when we will have packages for these distributions:
- [x] Ubuntu/Debian
- [x] Fedora
- [x] OpenSUSE (#159)
- [x] Arch LInux (AUR) (#153)

**Comment by viperML** [comment]
Hello, I am currently writing an ebuild for package distribution in Gentoo.

As you have mentioned, NPM is not well supported, and in Gentoo it involves manually disabling the network sandbox for the package. This not only triggers some automated QA warnings, but also concers me about reproducibility.

Distribution of the `bismuth.kwinscript` in the releases would be an easy solution.

The ebuild is hosted [here](https://github.com/viperML/viperML-overlay/blob/testing/kde-misc/bismuth/bismuth-2.0.0.ebuild). As for the PR to include this in the `README.md`, I will wait a bit in case something changes involving the kwinscript.

**Comment by gikari** [comment]
How would distribution of all build artifacts in the GitHub releases would sound? It would include an archive of build folder, including the `.kwinscript` package.

**Comment by gikari** [comment]
The example is here: https://github.com/gikari/test-bismuth-ci/releases/download/v3.0.0/build-artifacts.tar.gz

**Comment by viperML** [comment]
Looks good to me :+1:

**Comment by HanabishiRecca** [comment]
Some concerns:
1. Need a flag/option for `build.sh` to skip TS stage and script zipping stage. To clarify, here is how we doing it in Arch package now - [link](https://aur.archlinux.org/cgit/aur.git/tree/build.sh.patch?h=kwin-bismuth&id=f76ce412924a2aea69e30cd6aabadae28c2358ee).
2. In `package.json` move `esbuild` from `devDependencies` to just `dependencies`. Because it is the only package that needed to build. For now we are using dirty way `npm i -P --production esbuild@'^0.12.26'`, but in good case it should be just `npm i --production`.

**Comment by gikari** [comment]
> Some concerns:
> 1. Need a flag/option for `build.sh` to skip TS stage and script zipping stage. To clarify, here is how we doing it in Arch package now - [link](https://aur.archlinux.org/cgit/aur.git/tree/build.sh.patch?h=kwin-bismuth&id=f76ce412924a2aea69e30cd6aabadae28c2358ee).
> 2. In `package.json` move `esbuild` from `devDependencies` to just `dependencies`. Because it is the only package that needed to build. For now we are using dirty way `npm i -P --production esbuild@'^0.12.26'`, but in good case it should be just `npm i --production`.

1. Ok
2. Well, esbuild is not required for the script to operate. It's a clear build time dependency. Of course our case here is special and we are not a traditional NPM package, but it seems like substituting one hack with another.

Either way, both if those problems should go away, if using the build-artifacts from releases, right?

**Comment by HanabishiRecca** [comment]
> Either way, both if those problems should go away, if using the build-artifacts from releases, right?

No, this is not related thing. In AUR prebuilt artifacts can be used in separate e.g. `-bin` package, but main package are supposed to be built from the source if possible.

**Comment by gikari** [comment]
> > Either way, both if those problems should go away, if using the build-artifacts from releases, right?
> 
> No, this is not related thing. In AUR prebuilt artifacts can be used in separate e.g. `-bin` package, but main package are supposed to be built from the source if possible.

If the package is built **supposed** to be built from source **by the user**, why is it a problem to:
1. Use TS for checks (previously in Krohnkite TS was used to bundle as well) and produce a kwinpackage package? Speed and dependencies optimization?
2. Install all dev dependencies instead of production ones?

**Comment by HanabishiRecca** [comment]
Yes, build process optimization. Even with just `esbuild` there are concerns about slow npm work. Just not bothering a user with unnecessary checks that already were done by project author and then package maintainer. Particular release snapshot is a static thing.

**Comment by HanabishiRecca** [comment]
@gikari, build artefacts for 2.0.1 are unusable. Obviously packed wrong files.
```
CMake Error at kcm/cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "/__w/bismuth/bismuth/src/kcm/bismuth_config.kcfg": No such file or
  directory.
```
Also this is strange that prebuilt thing requires `cmake`. Maybe you will provide `cmake --install` end result?

**Comment by gikari** [comment]
> @gikari, build artifacts for 2.0.1 are unusable. Obviously packed wrong files.
> 
> ```
> CMake Error at kcm/cmake_install.cmake:46 (file):
>   file INSTALL cannot find
>   "/__w/bismuth/bismuth/src/kcm/bismuth_config.kcfg": No such file or
>   directory.
> ```
> 
> Also this is strange that prebuilt thing requires `cmake`. Maybe you will provide `cmake --install` end result?

Build artifacts are provided, so that the packagers won't have to use NPM, it wasn't planned with CMake in mind. However, providing install step end result is reasonable. I will take a look a try to change the build accordingly.

**Comment by HanabishiRecca** [comment]
I understand. But anyway, seems like `cmake` build result contains absolute paths from the machine that built it. That's why `cmake --install` will fail fro others. Try it yourself.

**Comment by gikari** [comment]
@HanabishiRecca and others, what do you think about this release artifact: https://github.com/gikari/test-bismuth-ci/releases/download/v4.0.0/install-artifact.tar.gz ?

Will it solve all the problems? I want to replace the build artifact I am currently providing with this.

**Comment by HanabishiRecca** [comment]
@gikari, good. It contains all needed files. Rest can be done by packager.

**Comment by viperML** [comment]
Not sure if `share/icons/hicolor/icon-theme.cache` should be included in the tarball.

As for Gentoo, I'm only taking the kwin script and compiling the rest, so no problems with the new format.

**Comment by HanabishiRecca** [comment]
> Not sure if `share/icons/hicolor/icon-theme.cache` should be included in the tarball.

It shouldn't. In fact e.g. Arch won't even let you install it. But this is not significant, it's not hard to just remove the file.
There are also other minor concerns, like `kcm_bismuth.so` is unstripped and contains debug symbols (has 2 MB size instead of ~78 KB it should be). But in Arch build system strips files automatically, so this is also not an issue here.

**Comment by gikari** [comment]
> > Not sure if `share/icons/hicolor/icon-theme.cache` should be included in the tarball.
> 
> It shouldn't. In fact e.g. Arch won't even let you install it. But this is not significant, it's not hard to just remove the file.
> There are also other minor concerns, like `kcm_bismuth.so` is unstripped and contains debug symbols (has 2 MB size instead of ~78 KB it should be). But in Arch build system strips files automatically, so this is also not an issue here.

I could provide two tarballs with debug symbols and without.
As for icon cache, I am not sure where is it coming from. I use ECM function for icons management, so I may investigate why is it including it.

**Comment by pasqui23** [comment]
Context: I'm packaging for NixOS https://github.com/NixOS/nixpkgs/pull/145196
The biggest problem I've encountered is that the cmake build start at non standard start of "src/kcm", so I had to both add extra flags and copy src/ in build/

**Comment by gikari** [comment]
> Context: I'm packaging for NixOS [NixOS/nixpkgs#145196](https://github.com/NixOS/nixpkgs/pull/145196) The biggest problem I've encountered is that the cmake build start at non standard start of "src/kcm", so I had to both add extra flags and copy src/ in build/

In the recent PR I introduced CMake for whole building process instead of scrips. Check it out.

**Comment by gikari** [comment]
The 2.1.0 release is out with the artifacts (both with debug symbols and without). You can check them out.

**Comment by HanabishiRecca** [comment]
Btw maybe there is some sense to include licenses into the build archives.

**Comment by volitank** [comment]
Hello. I am working on a debian .deb package. Is it a requirement for it to be in an Ubuntu ppa? I don't have any experience managing ppa's, but I run my own repo for Debian sid that I was planning on hosting it on.

All of my packages are signed with my GPG key and even apt source works. For bismuth, users can either add the repo or they can download the .deb directly if they would like.

Right now I have only tested the package on Debian Stable and Sid, but they should work on ubuntu at least 21.04+, Maybe even older. I could work on a bismuth only repo as well if you would prefer that. Wouldn't be too difficult

**Comment by gikari** [comment]
> Hello. I am working on a debian .deb package. Is it a requirement for it to be in an Ubuntu ppa? I don't have any experience managing ppa's, but I run my own repo for Debian sid that I was planning on hosting it on.
> 
> All of my packages are signed with my GPG key and even apt source works. For bismuth, users can either add the repo or they can download the .deb directly if they would like.
> 
> Right now I have only tested the package on Debian Stable and Sid, but they should work on ubuntu at least 21.04+, Maybe even older. I could work on a bismuth only repo as well if you would prefer that. Wouldn't be too difficult

The package, that is universal for Debian and Ubuntu, is welcome.
