### ISSUE TITLE
[Bug]: Bismuth wont tile windows

### ISSUE THREAD

**Issue by Akselmo** [Bismuth-Forge/bismuth#154]
### Summary

Hi, I upgraded from the old Bismuth script to the new one with the npm.

However now my windows wont tile at all.

When I restart kwin_x11, I get the following

```
OpenGL vendor string:                   AMD
OpenGL renderer string:                 AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.40.0, 5.11.0-38-generic, LLVM 12.0.0)
OpenGL version string:                  4.6 (Compatibility Profile) Mesa 21.3.0-rc3
OpenGL shading language version string: 4.60
Driver:                                 RadeonSI
GPU class:                              Arctic Islands
OpenGL version:                         4.6
GLSL version:                           4.60
Mesa version:                           21.3
X server version:                       1.20.11
Linux kernel version:                   5.11
Requires strict binding:                yes
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no
qml: [Bismuth] Initiating the script
kwin_core: XCB error: 10 (BadAccess), sequence: 2978, resource id: 1744, major code: 142 (Composite), minor code: 2 (RedirectSubwindows)
```

I tried to relog and restart PC but they didnt help. :(

### Steps to Reproduce

1. Install bismuth from source with npm
2. Windows wont start tiling

### Expected behavior

Windows would start to tile automatically like always

### Bismuth version

2.0.0

### KDE Plasma version

5.21.4

### The platform KWin is running on

X11

### Additional context

Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-38-generic
OS Type: 64-bit
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15,5 GiB of RAM
Graphics Processor: AMD Radeon ™ RX 480 Graphics

**Comment by Akselmo** [comment]
Upgrading Kubuntu didn't help

`Operating System: Kubuntu 21.10
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-20-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15,5 GiB of RAM
Graphics Processor: AMD Radeon ™ RX 480 Graphics`

**Comment by gikari** [comment]
I will try to reproduce the issue in the VM later. Seems interesting, since the log says, that the script started: `qml: [Bismuth] Initiating the script`.

**Comment by Akselmo** [comment]
Is there any way to help you debug this? See more logs for example?

**Comment by Akselmo** [comment]
Hey I found the bug!!

In window rules, if you have comma after the last item, it fails reading the window rules and floats everything by default.
![image](https://user-images.githubusercontent.com/13801236/140395575-7d35d446-dc2f-45bf-a312-346e27c25c6f.png)

Removing that solved my problem

**Comment by gikari** [comment]
This happens due to bad UI/UX for adding rules. Transformed this into #167

**Comment by gikari** [comment]
Although, could you test it wind #168 ? Maybe that will fix the issue.

**Comment by Akselmo** [comment]
Hey, sorry I forgot to test this earlier. Just gave it a go and now the issue is fixed for my end too.
