### ISSUE TITLE
[Bug]: Missing settings after installing ver 2.0

### ISSUE THREAD

**Issue by JoseConseco** [Bismuth-Forge/bismuth#161]
### Summary

After installing new 2.0 release I have empty Windows Tiling options (I'm on manjaro): 

![image](https://user-images.githubusercontent.com/13521338/140523322-4978373b-13f3-4396-8d39-1ab18a5a847a.png)

Before that I could access tiling options from KWin Scripts - but now Bismuth config is missing there too: 
![image](https://user-images.githubusercontent.com/13521338/140523784-07cb977e-4011-4f60-b23f-faf7003cb0f8.png)

### Steps to Reproduce

1. Install following  readme
2. restart
3. Settings for windows tilling are missing

### Expected behavior

I should be able to access tiling options in ver 2.0 on Manjaro system. 

### Bismuth version

2.0 (latest daily) 

### KDE Plasma version

5.22.5

### The platform KWin is running on

X11

**Comment by chrtlover** [comment]
If you installed through the aur package, please reinstall the package by removing and installing it again, it happened to one guy there.

**Comment by JoseConseco** [comment]
Thx, it worked using aur. Maybe info about it could be added to docs?

**Comment by jdzla** [comment]
I have a similar issue in KDE Neon. I am not sure how to fix or what this shared library is referring to. 
![skrinsyatz](https://user-images.githubusercontent.com/5458165/141735227-c132de6c-115e-4a1a-ad0a-d5f98e570895.png)



Bismuth Version: 2.1.0 (the one in master)
KDE Plasma Version: 5.23.3 on Wayland
Qt Version 5.15.3

I hope that you can help me solve it. thanks.

**Comment by gikari** [comment]
> I have a similar issue in KDE Neon. I am not sure how to fix or what this shared library is referring to. 
> 
> Bismuth Version: 2.1.0 (the one in master) KDE Plasma Version: 5.23.3 on Wayland Qt Version 5.15.3
> 
> I hope that you can help me solve it. thanks.

I just tested the installation withing the KDE Neon WM, and it just works. You might want to reinstall.

**Comment by BearOutThere** [comment]
I'm on Neon.  Just upgrated to Plasma 6 and am having the same issue.  Installed and reinstalled kwin-bismuth with apt several times but the Window Tiling item still not appearing under Window Management settings.   What to do?
