### ISSUE TITLE
[FEATURE]: Ability to focus windows on different screens with Bismuth: Window Focus command.

### ISSUE THREAD

**Issue by KaosBunny** [Bismuth-Forge/bismuth#169]
### Summary

Currently with multiple screens, moving from a node/window on screen A to a node/window on screen B doesn't work with the "Bismuth: Focus [Left/Down/Up/Right] Window" command or the "Bismuth: Focus [Next/Previous] Window:" command as the window focus commands are restricted to a single screen.

### A clear and concise description of what you want to happen

I want to be able to move from window to window across screens using the cardinal direction commands.

Say I have 2 screens and I'm focused on a window at the edge of screen A and want to move to a window on screen B that is "next door" so to say.

Before move:
![Image](https://user-images.githubusercontent.com/81906761/140720128-263e595d-4537-4f4e-bd99-4d01d30fda0f.png)

After hitting (for example) Meta + L
![Image](https://user-images.githubusercontent.com/81906761/140720031-7a7d6dd0-f4cf-4526-8ace-7aea00b09d9d.png)

### A clear and concise description of any alternative solutions or features you've considered.

You can currently achieve something similar using the Switch Next/Previous Screen option from KWin, but this requires two completely separate keybinding.

An implementation of this could be to just check whether you are at the furthest window in any direction and then if so, send the switch screen focus command instead. (Forgive me if it's not that simple, I have... pretty much no idea how this works.)

**Comment by gikari** [comment]
This annoys me too 😄 That's why I am using native KWin shortcuts for focusing windows to the left and right. I think we are duplicating functionality here I bit, so I'm planning to remove these shortcuts in the next major version. 

Would these native shortcuts work for you? They are called "Switch to Window to the Left/Right" and "... Above/Below" respectively.

**Comment by KaosBunny** [comment]
Yes! That actually works perfectly, thank you. I'm not exactly sure how I missed the built in KWin ones.

**Comment by SalmanFarooqShiekh** [comment]
@gikari Any way to do the same for moving windows across screens?
