### ISSUE TITLE
[FEATURE]: Separate layouts for each Screen

### ISSUE THREAD

**Issue by phrxmd** [Bismuth-Forge/bismuth#170]
### Summary

When I have two screens of different sizes, I would like to be able to use one layout on the small screen, and another on the large screen.

### A clear and concise description of what you want to happen

Currently I can select separate layouts per activity and per virtual desktop, and if I'm unhappy with the tiling on a screen I can disable the tiling entirely for that screen. 

However, often I just would like to use the screen real estate better by having a different layout on a smaller screen (such as my laptop monitor) vs. on a larger screen (such as the larger monitor on my desktop). 

So I would also like to have separate layouts not only for each Activity and for each Virtual Desktop, but also for each Screen, if possible. 

In case this gets confusing UI-wise, it would also be nice to have some kind of neat interface in the KCM that shows which layout is currently configured where (I opened a separate FR for that in #171).

**Comment by gikari** [comment]
Hm, I use different layouts on different screens, so it's already possible, isn't it?

**Comment by phrxmd** [comment]
Sorry, that's indeed what it does. It looks like I was being stupid, please ignore this FR:

**Comment by gikari** [comment]
No problem :)
