### ISSUE TITLE
[Bug]: Unfocused windows are being moved underneath other when being dragged

### ISSUE THREAD

**Issue by verahawk** [Bismuth-Forge/bismuth#190]
### Summary

Unfocused windows are being moved underneath other when being dragged.

### Steps to Reproduce

1. Make sure that Window Management > Window Behavior > Windows Action > `Meta + Left click` is set to just `Move`.
2. Make sure that Window activation policy is set to "Focus follow mouse" or lower.
3. Open some windows.
4. Focus some window, then drag other, unfocused one with `Meta + Left click`.
5. Observe how it goes underneath other windows.

### Expected behavior

Any dragged window should always be on top of others, even if it's unfocused.

### Bismuth version

master

### KDE Plasma version

5.22.5

### The platform KWin is running on

X11

**Comment by gikari** [comment]
Is this reproducible only with Bismuth enabled?

**Comment by Daxtorim** [comment]
>Is this reproducible only with Bismuth enabled?

No, this is a quirk of kwin. It's not even related to "focus follows mouse". Moving a window with `Meta + Left click` does not *raise* that window to the front, it stays where it is relative to other windows (in front or behind). Even with "focus follows mouse" there is still a distinct difference between *focusing* a window and *raising* it to the front.

Might be worth opening a bug report upstream.
