### ISSUE TITLE
[FEATURE]: Hide the script entry in the system settings?

### ISSUE THREAD

**Issue by verahawk** [Bismuth-Forge/bismuth#191]
### Summary

Now, that Bismuth uses KCM for the configuration, this entry does practically nothing.

`X-KWin-Exclude-Listing=true` could be used to hide it in the KWin Scripts tab so as not to confuse users.

What do you think?

### A clear and concise description of what you want to happen

n/a

**Comment by gikari** [comment]
I wanted to do that, but didn't know how.

> X-KWin-Exclude-Listing=true

If this works, that would be awesome!

**Comment by alex1701c** [comment]
There have been a few concerns on the KDE side about hiding specific scripts. Is the goal of this to make it completely "invisible" from the KWin scripts KCM or would hiding the config be enough?
Then users could see that it is there, but can only interact with the KCM by opening it directly in systemsettings.

**Comment by ikajdan** [comment]
If I recall correctly, we did it to make Bismuth appear more integrated into the Plasma. Basically, there is a KCM named Window Tiling, and that way it appears like a native feature to the end-user.
Furthermore, before that the configuration was done through the KWin scripts entry, and we didn't want to confuse users after we have moved it to a separate module.

**Comment by alex1701c** [comment]
But it is possible to still list a plugin without showing it's KCM. Would that be acceptable for you?

**Comment by ikajdan** [comment]
Good to know, however it seems that the development of Bismuth has stalled anyway.
