### ISSUE TITLE
[DEV]: Build with KDE desktop installed in Ubuntu 20.04

### ISSUE THREAD

**Issue by peara** [Bismuth-Forge/bismuth#199]
### Summary

I built Bismuth from source in a KDE Neon and it worked fined.
Then I have another computer with Ubuntu 20.04 and KDE desktop installed. 
I tried to build Bismuth again but the process is lengthy and really complicated.
I'd appreciate any help on this as I have been trying for 2 days without much success.

What I have tried:
- Built Qt 5.15 from source.
- Install KF5 by trying to add ppa as in https://community.kde.org/Get_KDE_Software_on_Your_Linux_Distro#Kubuntu but no 5.85 was found. It seems Ubuntu 20.04 was too old for those.
- Build KF5 from source but too complicated with different kind of errors.

On the other hand, is the dependency on Qt 5.15 and KF5 5.85 justified as Qt 5.12 and KF5 5.68 can be easily installed for Ubuntu 20.04.

**Comment by gikari** [comment]
For KDE Frameworks the version may be lowered, as I just selected the one from the Fedora repos, If I recall correctly.

For Qt I picked a recent version, so I could use the recent API, so I don't have to write C++ Marco to pick the non deprecated version of it.

Additionally, Plasma and KWin versions on Kubuntu are old and I depend on theirs' QML API, so supporting it would be more difficult.

In the end, I could try to accommodate to Qt 5.12, but couldn't give any promises.

I think ideally the version of Bismuth should be synced to the version of Plasma to prevent potential breakages, but

**Comment by gikari** [comment]
Ideally, the Bismuth releases should be synced with the KDE Plasma releases in the future (possibly via [incubation](https://community.kde.org/Incubator)), so that the users of old Plasma releases could install old Bismuth (this would not be applicable for Ubuntu 20.04 unfortunately).

**Comment by peara** [comment]
Thank you, I see that those libraries are necessary.
I have tried to remove the check for minimum requirement of both Qt and KF5 and encountered errors because of various components. So it might not be easy to do so.
Please close this if you see fit. I would try to update to Ubuntu 21.04 instead.
