### ISSUE TITLE
[Bug]: Can't maximize windows: the script pretends to keep tiling them

### ISSUE THREAD

**Issue by alxlg** [Bismuth-Forge/bismuth#207]
### Summary

Basically it's the same I reported here for Krohnkite:

https://github.com/esjeon/krohnkite/issues/64

There is a fix there in the comments that works for Krohnkite but not in Bismuth

### Steps to Reproduce

1. Try to maximize a tiled window, it will be kept tiled in a sort of broken state

### Expected behavior

When I maximize a window it should actually be maximized

If I make the window float and THEN maximize it it's OK but having to float/re-tile each time I want to maximize/de-maximize is annoying

### Screenshots

If I maximize a tiled window I get this (no decoration, window still tiled):

![](https://user-images.githubusercontent.com/26327475/75903679-35b30a80-5e42-11ea-939a-e6a8d06806c4.png)

Instead if I make it float first the THEN maximize I get the expected behavior:

![](https://user-images.githubusercontent.com/26327475/75903723-4794ad80-5e42-11ea-95d2-a16e121d03ed.png)

### Bismuth version

2.1.0

### KDE Plasma version

5.23.3

### The platform KWin is running on

Wayland

### Additional context

The issue is present in both X11 and Wayland sessions

**Comment by gikari** [comment]
This was fixed in #205
