### ISSUE TITLE
Moving windows with the mouse and retiling them

### ISSUE THREAD

**Issue by volitank** [Bismuth-Forge/bismuth#228]
Hello. Trying out your wm and one thing that I wonder if I'm doing wrong or can't find the option.

When I grab a tiled window with the mouse and move it then it seems to stay floated. I can press meta+f to retile it but I wonder if there is an option somewhere for the windows to automatically retile if they already were tiled before being moved?

If not I think this would be a useful feature to implement.

**Comment by Nano-Ocelot** [comment]
This also happens to me a lot. I've noticed it happens basically every time if I have 'screen 1' focused and move a window on 'screen 2' with meta+left-click drag to a new position on 'screen 2.' It also happens sometimes even on the current screen that's focused but I can't quite pin down the scenario to recreate that.

**Comment by volitank** [comment]
Today I cannot seem to reproduce the issue. Restarting must have fixed it

**Comment by gikari** [comment]
I didn't understand what you wanted, but if the issue is fixed for you, then that's great!
