### ISSUE TITLE
[Bug]: Missing dependency when building from source?

### ISSUE THREAD

**Issue by zk453** [Bismuth-Forge/bismuth#229]
### Summary

I followed the steps when installing from source but there is an error when trying to activate bismuth through the settings menu.
![Screenshot_20211214_023314](https://user-images.githubusercontent.com/36011542/145911065-4e0b111b-255c-4c51-b538-9c75e9be3315.png)
Is there a problem with my ubuntu installation? or there is a missing dependency?
im on kubuntu 21.04

### Steps to Reproduce

Just building by source and then opening the settings

### Expected behavior

Menu to be showing properly

### Screenshots

![Screenshot_20211214_023808](https://user-images.githubusercontent.com/36011542/145911526-a9fd91e4-7fe9-4410-923c-89ec513c1487.png)

### Bismuth version

2.2.0

### KDE Plasma version

5.21.4

### The platform KWin is running on

X11

### Additional context

when running systemsettings5 from console: 
```
file:///usr/share/kpackage/genericqml/org.kde.systemsettings.sidebar/contents/ui/SubCategoryPage.qml:158:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/share/kpackage/genericqml/org.kde.systemsettings.sidebar/contents/ui/SubCategoryPage.qml:148:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/templates/private/ScrollView.qml:73:5: QML Binding: Not restoring previous value because restoreMode has not been set.
This behavior is deprecated.
You have to import QtQml 2.15 after any QtQuick imports and set
the restoreMode of the binding to fix this warning.
In Qt < 6.0 the default is Binding.RestoreBinding.
In Qt >= 6.0 the default is Binding.RestoreBindingOrValue.

file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/templates/private/ScrollView.qml:73:5: QML Binding: Not restoring previous value because restoreMode has not been set.
This behavior is deprecated.
You have to import QtQml 2.15 after any QtQuick imports and set
the restoreMode of the binding to fix this warning.
In Qt < 6.0 the default is Binding.RestoreBinding.
In Qt >= 6.0 the default is Binding.RestoreBindingOrValue.

file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/templates/private/ScrollView.qml:73:5: QML Binding: Not restoring previous value because restoreMode has not been set.
This behavior is deprecated.
You have to import QtQml 2.15 after any QtQuick imports and set
the restoreMode of the binding to fix this warning.
In Qt < 6.0 the default is Binding.RestoreBinding.
In Qt >= 6.0 the default is Binding.RestoreBindingOrValue.

file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/templates/private/ScrollView.qml:73:5: QML Binding: Not restoring previous value because restoreMode has not been set.
This behavior is deprecated.
You have to import QtQml 2.15 after any QtQuick imports and set
the restoreMode of the binding to fix this warning.
In Qt < 6.0 the default is Binding.RestoreBinding.
In Qt >= 6.0 the default is Binding.RestoreBindingOrValue.
```

**Comment by gikari** [comment]
Could you run the "kcmshell5 kcm_bismuth" from console?

**Comment by zk453** [comment]
when running kcmshell5 kcm_bismut i get this:
![Screenshot_20211215_200902](https://user-images.githubusercontent.com/36011542/146241595-0ab11bae-a5a1-49fd-b865-872e0b3b9f83.png)
with this: 
![Screenshot_20211215_200956](https://user-images.githubusercontent.com/36011542/146241736-c58a3ead-d6c8-4e3b-a1ad-d58ed2b43e93.png)

Also i did do-release-upgrade to update my system in hopes i find the missing library and my config has changed
to 
![Screenshot_20211215_201125](https://user-images.githubusercontent.com/36011542/146241866-b25a5bde-e8ef-4d23-9afc-54d8b9babbb7.png)
but the problem still persists

**Comment by zk453** [comment]
**UPDATE** 
There was a problem when sourcing environment variables from prefix.sh because i switched my shell to zsh, i exported the variables by hand and it got fixed

**Comment by gikari** [comment]
What do you mean by that? You don't need to source/export anything. Once you install everything, it should just work.

**Comment by zk453** [comment]
When building from source files there is a file created in the build directory called prefix.sh with contents:
![Screenshot_20211216_204201](https://user-images.githubusercontent.com/36011542/146429925-afab9d1c-cb5d-4777-8f2b-3b68889253ce.png)
When running the commands manualy, kcm managed to find the plugin and i managed to open the settings and configure bismuth.
If you have no problems with people that have oh-my-zsh and kubuntu then this is probably a user error on my part by misconfiguring something

**Comment by gikari** [comment]
Ok, so the issue seems to be solved. Great to hear. :+1:
