### ISSUE TITLE
How To Customize Shortcuts?

### ISSUE THREAD

**Issue by earlb3** [Bismuth-Forge/bismuth#234]
I can't figure out how to customize shortcuts.

For instance, I want to increase the master size but no default shortcut is defined, and i can't figure out how to do it from the keyboard shortcuts page?

**Comment by gikari** [comment]
The default shortcut for master size is Ctrl+I and Ctrl+D.

You can change the default shortcuts in System Settings > Shortcuts > KWin (There will be shortcuts prefixed with “Bismuth:").

Although it is planned to make the shortcuts more discoverable.

**Comment by earlb3** [comment]
Oh cool, thank you for the quick reply.

I had another tiling window plugin installed and when i tried to remove
those shortcuts, i ended up removing all of them including bismuth.

However, a reinstall of bismuth brought them back.

Awesome program!

Thank you!
