### ISSUE TITLE
[FEATURE]: Monocle layout option to make windows opaque

### ISSUE THREAD

**Issue by kauesena** [Bismuth-Forge/bismuth#235]
### Summary

If your terminals have a degree of transparency, when in monocle mode, it may generate confusion to see glimpses of the other windows background. It may be purely distracting too. For example, seeing a dimed version of the last web page you've opened displayed behind your text editor. 

It would be great to be able to make windows opaque when in this mode, or at least to have the background displayed behind them instead of the other windows. 

### A clear and concise description of what you want to happen

In monocle layout, focused window not to show the contents of the other ones despite their having transparent background in other tiling modes.

### A clear and concise description of any alternative solutions or features you've considered.

I considered using the minimize unfocused windows option, but this turns on the animation of minimizing and maximizing windows when changing focus.

### Additional info

If kwin does not offer an easy way to turn off transparency, perhaps this could be achieved by setting a solid background of a choosen colour behind the focus window. Or even the desktop wallpaper being placed behind them.

**Comment by gikari** [comment]
> It would be great to be able to make windows opaque when in this mode, or at least to have the background displayed behind them instead of the other windows.

Bismuth cannot control windows opacity, when the opacity comes from the app itself (e.g. Konsole terminal area opacity).

> I considered using the minimize unfocused windows option, but this turns on the animation of minimizing and maximizing windows when changing focus.

Not sure about the details, but this might be a bug. You should report this.

For the use case you described, there is "minimized unfocused mode", that you tried to use. If the result of using it is buggy, then the bug should be fixed.
