### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by niksingh710** [Bismuth-Forge/bismuth#238]
### Summary

I have one monitor connected to my laptop and have set `Meta+Shift+left` or `Meta+Shift+right` shortcuts to move the window to another screen.

when I try to move the window sometimes it works fine sometimes it glitches out.

### Steps to Reproduce

Connect another monitor.
Try using `Meta+Shift+left` or `Meta+Shift+left` to move window at other screen.

### Expected behavior

Should Send the window to other Monitor. 

### Bismuth version

cloned from the git  with last commit `8419654e6b4c2a3cf455e925db61bf0bdac76b38`

### KDE Plasma version

5.23.4

### The platform KWin is running on

X11

**Comment by verahawk** [comment]
Duplicate of #218

**Comment by niksingh710** [comment]
Closing this one created without checking properly as this was Duplicate of #218.
