### ISSUE TITLE
[Bug]:  GTK Application Border

### ISSUE THREAD

**Issue by niksingh710** [Bismuth-Forge/bismuth#239]
### Summary

Chrome has a weird border on any layout.
even on monocle layout too.

### Steps to Reproduce

Add any chrome app and open it.

### Expected behavior

Border should be attached to the window.

### Screenshots

![Screenshot_20211228_105616](https://user-images.githubusercontent.com/60490474/147531241-034fda08-ac09-4017-8313-d2704d4a63fc.png)
![Screenshot_20211228_105746](https://user-images.githubusercontent.com/60490474/147531421-c53b480c-52cb-46ad-b105-03541b30f1c8.png)

### Bismuth version

cloned from the git  with last commit `8419654e6b4c2a3cf455e925db61bf0bdac76b38`

### KDE Plasma version

5.23.4

### The platform KWin is running on

X11

**Comment by niksingh710** [comment]
EDIT: Not in chrome app but in every GTK app.

**Comment by gikari** [comment]
Is this bug reproducible with the Bismuth turned off? (System Settings > Window Management > Window Tiling > Enable Window Tiling)

**Comment by niksingh710** [comment]
yes, when Bismuth is turned off then also the bug remains.

**Comment by gikari** [comment]
In that case, it's probably not a Bismuth bug. Check out your window rules (System Setting > Window Management > Window Rules) and window decoration rules (System Settings > Appearance > Window Decoration > Pencil Icon on your current decoration > Window Specific Overrides).
