### ISSUE TITLE
[FEATURE]: Option for set default Window Layouts

### ISSUE THREAD

**Issue by ForteDexe** [Bismuth-Forge/bismuth#242]
For example: I want to use Spiral Layout as my main layout when login, but I have to switch the layout multiple times until reach it.
If possible, I would like the spiral layout to open a new window at the bottom right corner, instead of the center screen.
And I have one more question, what exactly 'rotate part' shortcut do ?

**Comment by Major2828** [comment]
Hi @ForteDexe there is already a issue for that #74 and also a PR #117 it should be added soon, i hope :smiley: . I am also waiting for this feature. Rotate part is only available on the tile Layout, but i dont know what it do, i see no changes. 
Have a nice start in 2022 :fireworks:
