### ISSUE TITLE
[FEATURE]: Disable automatic change dragging window to float

### ISSUE THREAD

**Issue by ForteDexe** [Bismuth-Forge/bismuth#244]
### Summary

When dragging a window between multiple workspace, it automatic change drag window to float type, I have to press a shortcut to change that window to tile type again, it is an inconvenience

### A clear and concise description of what you want to happen

An option to disable dragging window auto change to float type

**Comment by Nano-Ocelot** [comment]
This sounds like the bug I referenced here. https://github.com/Bismuth-Forge/bismuth/issues/231#issuecomment-996371876

**Comment by ForteDexe** [comment]
> This sounds like the bug I referenced here. [#231 (comment)](https://github.com/Bismuth-Forge/bismuth/issues/231#issuecomment-996371876)

Yes, but it is not by virtual desktop issue, normally you can drag a window a little bit from its original position, that windows will switch to float mode, no need to move it between virtual desktop to re-create the issue

**Comment by gikari** [comment]
I'm maybe missing something, but dragging window should work like this:
- If window is dragged only by a few pixels out of its tiled position, then nothing changes - window is tiled back.
- If window is dragged far out of its position and it's center is around the center of another tiled window, then it takes the place of that window.
- If the window is dragged far out of its position, but its center is not near the center of another window, then the window floats.

What exactly do you not like in the above behavior?

**Comment by verahawk** [comment]
>     * If the window is dragged far out of its position, but its center is not near the center of another window, then the window floats.

I wish that this behavior could be disabled. If I ever need to float a window, I just use the shortcut.

I find myself accidentally dragging windows out of the tiling mode when using `Meta+LMB` to rearrange them. In fact, when I installed Bismuth for the first time, I thought it was a bug!

**Comment by ForteDexe** [comment]
yep, exactly like @verahawk describe above, an option to disable that feature.

**Comment by gikari** [comment]
Ah, ok, that make sense. Not sure if it should be the default.

**Comment by kauesena** [comment]
@ForteDexe What is the shortcut you use to tile back the window which started to float? In Khronkite, similar things happened and I used the "float all" twice to make all windows be tiled.

**Comment by kauesena** [comment]
Oh. The shortcut "Bismuth: Toggle Active Window Floating" solves it. 
It would be good to have a shortcut to tile back all floating windows on the present workspace.

**Comment by HelmicNewciv** [comment]
Just as a cherry on top, recommended this to someone who wanted a replacement for Fancyzones on Windows - this option seems to make it replicate that functionality pretty well.  Good job!
