### ISSUE TITLE
[Bug]: Vertical Latte-Dock Panel Covering Tiled Windows

### ISSUE THREAD

**Issue by Nano-Ocelot** [Bismuth-Forge/bismuth#245]
### Summary

When using the latest latte-dock on X11, placing a vertical panel on the left side of screen covers tiled windows and the only remedy is to restart kwin. If latte-dock is restarted at any point it covers tiled windows again. Horizontal panel on the top doesn't seem to have the issue. Also the windows properly dodge the panel when in floating mode, only when tiled do they have this issue.

### Steps to Reproduce

1. Using latest latte-dock version, create vertical latte-dock panel on left side of screen
2. Restart latte-dock

### Expected behavior

Tiled windows should dodge the panel just like floating windows do.

### Screenshots

![Screenshot_20220106_183802](https://user-images.githubusercontent.com/34014750/148467612-daf48829-7bd8-4d79-b48e-c8a25bb9eb34.png)

### Bismuth version

Latest Git Master Branch

### KDE Plasma version

5.23.4

### The platform KWin is running on

X11

**Comment by Nano-Ocelot** [comment]
I've also noticed that sometimes when the compositor is suspended it also causes tiled windows to go under the panel and kwin needs to be restarted to fix it.

**Comment by Nano-Ocelot** [comment]
No, does that mean I should submit a bug report on latte-dock's page?

**Comment by gikari** [comment]
In your case, probably yes, but I just added a Plasma panel and Bismuth didn't properly react to its addition.

If you change the layout of windows (from tiling to monocle, for example), do the windows "sense" the side panel presence?

**Comment by Nano-Ocelot** [comment]
No, changing the layout around doesn't fix the issue. I've tried everything I can think of and the only thing I've found that fixes it is restarting kwin. I've also noticed that this issue doesn't occur at all in Wayland.

**Comment by Nano-Ocelot** [comment]
This appears to be fixed after a couple boots using the latest latte-dock git master branch.
