### ISSUE TITLE
Colored borders

### ISSUE THREAD

**Issue by SkelyTony** [Bismuth-Forge/bismuth#247]
Hello, I'm just wondering how do I get colored borders like shown in demo?

**Comment by SkelyTony** [comment]
![Screenshot_20220107_190338](https://user-images.githubusercontent.com/78977752/148587116-f4453b10-f864-4852-b560-2f1bb7387718.png)
Also, KDE doesn't seem to listen to my minimum window s
![Screenshot_20220107_190457](https://user-images.githubusercontent.com/78977752/148587263-569da418-c782-4420-af1f-e788244b2f8f.png)
ize

**Comment by gikari** [comment]
I use [Classik  Window decoration](https://github.com/paulmcauley/classik) with [the tweaks](https://github.com/Bismuth-Forge/bismuth/blob/master/TWEAKS.md). 

> Also, KDE doesn't seem to listen to minimum window size rule

If you're able to tile System Settings with another window without overlapping on a small screen, it means the rule is working.

**Comment by SkelyTony** [comment]
Thank you for responding, KDE minimum size rule does make it not over lap when tiling in some cases, but there still seems to be a hidden minimum size. When settings is on the right side, part of it is not visible, since it overflowing from the monitor. When it's on left it still overlaps with apps on the right ( as provided in the screen shot). When the rule is applied it overlaps less, but nonetheless it still overlaps
![Screenshot_20220107_191740](https://user-images.githubusercontent.com/78977752/148588829-77e0f102-631b-4874-bc67-f48b548eddd8.png).

**Comment by gikari** [comment]
Here is my rule:

![Screenshot_20220107_212152](https://user-images.githubusercontent.com/14205339/148589095-49813265-9b38-46e9-bf50-520456a703bf.png)

Let me know if it works for you.

**Comment by SkelyTony** [comment]
@gikari I have copied them and they dont seem to work
![Screenshot_20220107_193956](https://user-images.githubusercontent.com/78977752/148591159-90b53094-e70d-4046-aaa6-904d1324ceaf.png)

**Comment by SkelyTony** [comment]
Also colored borders seem not to work
![Screenshot_20220107_194150](https://user-images.githubusercontent.com/78977752/148591407-118aa57a-b0fe-46d7-9096-2f4707c540b9.png)

**Comment by gikari** [comment]
> I have copied them and they dont seem to work

Are both of your windows tiled (i.e. not floating)? Try toggling the state via Win+F (Default shortcut)

Could you make sure, that the rule is working by disabling Bismuth and trying to resize the windows?

> Also colored borders seem not to work

This is bug in Plasma: https://bugs.kde.org/show_bug.cgi?id=439222

You could work around it by creating the color scheme, where there is no `[Colors:Header]` groups in it (You need to open the file with the text editor to remove them).

**Comment by SkelyTony** [comment]
> Are both of your windows tiled (i.e. not floating)? Try toggling the state via Win+F (Default shortcut)

yes, they are both tiled and when not tiled settings has a minimum
![Screenshot_20220107_195204](https://user-images.githubusercontent.com/78977752/148592538-149128af-77ef-4421-a39e-74c835858c92.png)
 size

**Comment by SkelyTony** [comment]
![Screenshot_20220107_195408](https://user-images.githubusercontent.com/78977752/148592769-c8fa9849-10eb-4f5f-9de9-2949a259d5d5.png)

what should be removed here?

**Comment by gikari** [comment]
> yes, they are both tiled and when not tiled settings has a minimum size

You should then report the bug upstream (to KDE Plasma/KWin devs): https://bugs.kde.org/

> what should be removed here? Both groups with all the lines below them.

**Comment by SkelyTony** [comment]
is it ok to just comment them out @gikari

**Comment by gikari** [comment]
I don't know :) It does not matter much, as long as you copied your color scheme and **not** editing the one in `/usr/share`

**Comment by SkelyTony** [comment]
I commented them out, they appear on floating windows too, is there a way to keep borders normal on floating windows and have the blue ones only on tiled windows?

**Comment by gikari** [comment]
Nope. It's impossible from our side.

**Comment by SkelyTony** [comment]
the title bar is still here, how do I remove them @gikari

**Comment by SkelyTony** [comment]
and thank you helping!

**Comment by gikari** [comment]
> the title bar is still here, how do I remove them @gikari

Here is the section from the tweaks file about that:

https://github.com/Bismuth-Forge/bismuth/blob/master/TWEAKS.md#removing-title-bars
