### ISSUE TITLE
[Bug]: Unable to get border colors

### ISSUE THREAD

**Issue by ShabirK21** [Bismuth-Forge/bismuth#260]
### Summary

I ran the provided script for get adding the frames in kdegloabl and tried adjusting my border size. But I still cant get border colors to appear.

### Steps to Reproduce

The border color set-up steps

### Expected behavior

Border colors for tiled windows, showing active and inactive windows

### Bismuth version

2.2.0-1

### KDE Plasma version

5.23.5

### The platform KWin is running on

X11

### Additional context

I'm using the bin version.

**Comment by ceeli** [comment]
I also had this Problem when using "Breeze Light" Colors. Switching to "Breeze" in Appearance -> Colors made it work for me. Only a workaround of course, don't know why it doesn't work with "Breeze Light".

KDE Version: 5.23.4
Bismuth version: 2.2.0

**Comment by gikari** [comment]
This is a bug in Plasma: https://bugs.kde.org/show_bug.cgi?id=439222

You could work around it by creating the color scheme, where there are no [Colors:Header] groups in it (You need to open the file with the text editor to remove them).

See also #247

**Comment by gikari** [comment]
Also, if you want the bug to be fixed ASAP - add to CC in the linked bug report.

**Comment by ShabirK21** [comment]
Thanks for the quick reply, ill look it into.

**Comment by robbins** [comment]
Same, I don't get border colors on Konsole windows.
