### ISSUE TITLE
[Bug]: Drag & drop a browser tab buggy with chromium

### ISSUE THREAD

**Issue by Napster2709** [Bismuth-Forge/bismuth#269]
### Summary

Dragging a tab out of a brower (tested with brave), breaks the tiling behaviour. The dragged tab default to full screen and can not be tilled. The browser of which the tab was coming from is now brocken too, in that no window moving shortcuts (meta+shift+arrow keys) or tilling are working.

I testet firefox, where it works just fine.
Opening a new brave instance works as intended

### Steps to Reproduce

1. Enable Bismuth
2. open a chromium based browser (brave as in my example)
3. Drag out a browser tab
4. The new tab will start as tiled (in preview while still in drag) and move to full screen once it is let loose

### Expected behavior

Dragged out brower tab should position itself inside a tileing spot.
Shortcuts should still be useable after dragging out a browser tab.

### Bismuth version

2.2.0.1

### KDE Plasma version

5.23.5

### The platform KWin is running on

X11

**Comment by gikari** [comment]
dup of #105
