### ISSUE TITLE
[Bug]: Is not changing border colors

### ISSUE THREAD

**Issue by fcsm1922** [Bismuth-Forge/bismuth#270]
### Summary

did everything as indicated in Tweaks after installation but there are no borders around the screen in principle ((
you can at least show screenshots where and what to change .... because. here ( Untick Use theme's default window border size and adjust the size (right from the checkbox).) I don't have such an item (( I use the latest version of kde plasma 5.23 

### Steps to Reproduce

go to setting

### Expected behavior

see borders around windows 

### Bismuth version

2.2.0

### KDE Plasma version

5.23

### The platform KWin is running on

X11

**Comment by gikari** [comment]
This is not a Bismuth bug, although the instructions should be updated to reflect the current bugged state of the proposed tweaks.md solution.
