### ISSUE TITLE
[Bug]: Plasma activities switcher forces tiled windows out of the way, and then the tiled windows get stuck like that. 

### ISSUE THREAD

**Issue by JonathanReeve** [Bismuth-Forge/bismuth#272]
### Summary

Switching activities to an activity with tiled windows causes those windows to move to the right, to make room for the activities switcher window. But when the activities switcher hides itself, the tiled windows stay in that position, i.e., with a noticeable gap. 

### Steps to Reproduce

1. Have two activities, each containing tiled windows
2. Switch between them
3. Notice that messes up your tiling

### Expected behavior

I expected to be able to switch activities without it messing with my tiled windows. 

### Bismuth version

???

### KDE Plasma version

5.23.5

### The platform KWin is running on

Wayland

**Comment by gikari** [comment]
Dup of #115
