### ISSUE TITLE
Question: how to ignore some zoom windows

### ISSUE THREAD

**Issue by tcoopman** [Bismuth-Forge/bismuth#274]
I'm not sure if this is the right place to ask this, if not please let me know where to ask it.

### Summary

When using [zoom](zoom.us) in a tiling layout, sometimes - for example when switching to a breakout room - zoom shows lot's of popup windows.

Some examples of these: 
![image](https://user-images.githubusercontent.com/45546/151320409-72303b7c-1ac3-4d4a-8860-a0dc915ef064.png)
![image](https://user-images.githubusercontent.com/45546/151320754-62d398e9-9ecb-4d27-a68b-e4f50b3d6a2f.png)

I'm wondering how I can tell bismuth to show these as floating windows, without having all meeting window floating

### A clear and concise description of what you want to happen

I'd like to have the zoom popup windows floating, but I don't see any good properties to differentiate the windows.

### Additional info

output of xprop for such a window:

```
NET_WM_DESKTOP(CARDINAL) = 0
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_NET_WM_VISIBLE_NAME(UTF8_STRING) = "zoom <2>"
_NET_WM_WINDOW_OPACITY(CARDINAL) = 4294967295
_NET_WM_ICON_GEOMETRY(CARDINAL) = 2284, 1567, 299, 33
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE
_KDE_NET_WM_ACTIVITIES(STRING) = "b7eca816-5597-42f4-972e-88c159b97995"
_NET_WM_USER_TIME(CARDINAL) = 9558105
_NET_WM_STATE(ATOM) = 
_NET_WM_ICON(CARDINAL) =        Icon (64 x 64):...

XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) = "zoom"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x40000d
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
                window id # of group leader: 0x40000d
WM_CLIENT_MACHINE(STRING) = "honor"
_NET_WM_PID(CARDINAL) = 3324
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 4194345
WM_CLASS(STRING) = "zoom", "zoom"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: 6, 791
                user specified size: 425 by 74
                window gravity: Static

```

**Comment by gikari** [comment]
Zoom does not put correct properties for its windows. You can add zoom to the ignore list and tile it manually with Win+F.

Seems like a good candidate for the default ignore list.
