### ISSUE TITLE
[FEATURE]: Support KDE Plasma 5.20.5

### ISSUE THREAD

**Issue by jgoerzen** [Bismuth-Forge/bismuth#285]
### Summary

Hi!  I was quite excited to hear about Bismuth today.  I am on Debian, which has 5.20.5 in the distro.  The docs state that 5.23 is required.  I do meet the Qt prerequisites.  It would be fantastic if this could work on 5.20.  Do we know what is in the way of that or how hard it would be?

### A clear and concise description of what you want to happen

Be able to run in Debian

### A clear and concise description of any alternative solutions or features you've considered.

I've been trying https://github.com/kwin-scripts/kwin-tiling which works, but isn't quite the level of features I'd like to see.

**Comment by gikari** [comment]
Did you try to install Bismuth from source and test it?

The Plasma requirements were specified quite arbitrary, so if it works on 5.20, the readme could be fixed.

**Comment by jgoerzen** [comment]
Hi,

I did manage to make it work!

In the top-level CMakeLists.txt, I had to change KF5_MIN_VERSION from 5.80.0 to 5.78.0 and that did the trick!
