### ISSUE TITLE
[Bug]: Bismuth does nothing, and seems to not be enabled after being enabled. (Opensuse Tumbleweed)

### ISSUE THREAD

**Issue by bplx** [Bismuth-Forge/bismuth#290]
### Summary

I'm using Opensuse Tumbleweed and nothing appears to be happening after installing Bismuth and enabling it.

### Steps to Reproduce

1. Install Bismuth through https://software.opensuse.org/package/bismuth.
2. Go to System Settings > Window Management > KWin Scripts.
3. Check off Bismuth.
4. Log out and log back in.

### Expected behavior

Windows to start tiling and keybinds to pop up.

### Bismuth version

Not sure, please tell me where to find it.

### KDE Plasma version

5.23.5

### The platform KWin is running on

X11

**Comment by gikari** [comment]
It seems like you are using a very old version of Bismuth, which wasn't updated by the packager. What repo is that?

You should be able to turn on Bismuth in the Window Management > Window Tiling category, not in the KWin scripts (see the screen shot in the readme).

**Comment by bplx** [comment]
Actually, i installed it via https://software.opensuse.org/package/bismuth; i think that may be a old repository. The reason for this is because i am not really sure how to use OBS (i recently just installed opensuse). Now that i think about it i was incorrect about my original statement that i installed it from the OBS repo.
The version appears to be 2.1.0-4.1, which i saw via Yast.

**Comment by gikari** [comment]
Okay, in that case please install Bismuth from the package linked in the Readme. 

But, please note, that packages listed in readme are not official and if you encounter an issue similar to this, please contact the packager first.
