### ISSUE TITLE
[Bug]: Resizing chrome windows sporadically works

### ISSUE THREAD

**Issue by andaag** [Bismuth-Forge/bismuth#291]
### Summary

If I open 2 chrome windows with a kde shortcut I can't drag to resize them.
If I drag one chrome tab down it ends up under? the other window, after changing from floating/non floating a few times I can resize them again.

NB : If this isn't immediately reproducible, let me know and I can try to get a video of the behavior or something like that.

### Steps to Reproduce

1. Go to a new virtual desktop
2. Open 2 chrome windows with a shortcut (or through krunner)
3. Try resizing them
4. After not getting a resize window, try opening another tab in one of the windows, then drag that "off" that tab into a new window. - I think it ends up behind the others? But it's hard to tell what's on top at that point. After changing floating on/off for a few of the windows it will start working again.

### Expected behavior

Resizing works consistently.

### Screenshots

My resize mouse pointer doesn't show up when I screenshot so I can't really demonstrate the behavior.

### Bismuth version

kwin-bismuth 2.3.0-1 from arch

### KDE Plasma version

5.24.0-1

### The platform KWin is running on

X11

**Comment by andaag** [comment]
I did not have this issue before, but the kde 5.24 update and the latest bismuth came at roughly the same time, so I'm not sure which of those updates or any is causing the problem.

It is a regression for me though.

**Comment by gikari** [comment]
Sorry, but I cannot reproduce your bug. The video demo would be helpful.

**Comment by andaag** [comment]
This was *completely* reproducible, but restarting my session (possibly after a few more updates) seems to have made it go away. (I did restart my session to confirm it wasn't a lingering issue before as well).

If this comes back again I'll get a video!

**Comment by andaag** [comment]
I'll keep this closed until I can reproduce it, but there is an issue here still.

Sometimes I can't resize 2 chrome windows next to each other, then when playing with the tabs I accidentally drag it into a floating window that that fixes it. I've tried 2 times now to get a recording of this issue but every time I do I can't figure out the steps to trigger it again!
