### ISSUE TITLE
[Bug]: kwin crashes on login with bismuth enabled

### ISSUE THREAD

**Issue by msmol** [Bismuth-Forge/bismuth#293]
### Summary

Logging in to a plasma session with bismuth enabled causes kwin / wayland to crash. 

Disabling it by marking `bismuthEnabled=false` in `~/.kwinrc` (either in another window manager or command line) allows me to to start a new plasma session, and re-enable bismuth, which then works fine until the next time I logout.

I have tried logging in through both SDDM as well as `startplasma-wayland` from command line, same result.

### Steps to Reproduce

1. Enable bismuth
2. Logout
3. Log back in
4. kwin crashes and brought back to SDDM or command line

### Expected behavior

Not crash

### Bismuth version

2.3.0

### KDE Plasma version

5.24.0 (but also 5.23.x)

### The platform KWin is running on

Wayland

### Additional context

See core dump:
[core_dump.txt](https://github.com/Bismuth-Forge/bismuth/files/8041887/core_dump.txt)

**Comment by maximushugus** [comment]
I also have this bug with KDE 5.24 using Wayland.
I can trigger the plasma crash by changing the display setting using mutliple monitors

**Comment by msmol** [comment]
> I suspect these are some side effects, that were introduced by the bugs of Plasma 5.24, but I cannot know for sure. 

I had the same issue on 5.23 and was hoping 5.24 would somehow fix the issue -- it did not.

**Comment by rejedai** [comment]
I have the same problem. 

Without a second monitor, everything works fine. But with the second one, even if I disable the first one in the kscreen settings, monitor turns on and session crashes.

**Comment by rejedai** [comment]
> From the core dump I'd say that enabling the system tray icon fails because the QML context isn't initialized yet.

Great, is there a quick way to fix this?

**Comment by gikari** [comment]
We are going to throw away the current tray icon and replace it with a new applet. If it causes the crashes, then I will remove it on master (it uses experimental API anyway).

**Comment by maximushugus** [comment]
The problem is still here with KDE 5.24 Wayland with Bismuth 3.0.0
