### ISSUE TITLE
[Bug]: In multi monitor, if I change the virtual desktop it change it for all monitors

### ISSUE THREAD

**Issue by aleOS2** [Bismuth-Forge/bismuth#295]
### Summary

If I go to the virtual desktop 2 in the monitor A, the monitor B go the desktop 2 (in i3 the monitor B remains unchanged)

### Steps to Reproduce

Change the virtual desktop by shortcut or applet and it change the virtual desktop for all monitors

### Expected behavior

Example if I go to the virtual desktop 2 in the monitor A, the monitor B remains unchanged

### Screenshots

https://user-images.githubusercontent.com/65780895/153713516-f06d4d0a-140a-41ab-8934-093ca12fb3e8.mp4

### Bismuth version

2.3.0-1 by Aur

### KDE Plasma version

5.24.0

### The platform KWin is running on

X11

### Additional context

I think I've said it all and you know what I mean

**Comment by verahawk** [comment]
Sadly, that's KWin limitation, it would be messy to implement it at Bismuth level.

**Comment by gikari** [comment]
Sadly, this is not what we can control. This is Plasma limitation. You should ask KWin devs to implement the behaviour you want at https://bugs.kde.org

**Comment by windowsrefund** [comment]
[Here is the feature request](https://bugs.kde.org/show_bug.cgi?id=107302) that has been open since 2005.
