### ISSUE TITLE
[DEV]: Not an issue, but Bismuth is now included in Ubuntu

### ISSUE THREAD

**Issue by eeickmeyer** [Bismuth-Forge/bismuth#299]
### Summary

Hi there! I've gone ahead and taken the existing packaging and brought it up to Ubuntu/Debian standards, and now it's included in Ubuntu Jammy Jellyfish (future 22.04)'s repository. 

Feel free to close this issue, but I just wanted to let you know. :)

**Comment by gikari** [comment]
It is actually kind of an issue, :) We need to add the info about the package in the README.md.

**Comment by gikari** [comment]
Do you have a link to the package? I don't see one, when I search in https://packages.ubuntu.com/

**Comment by eeickmeyer** [comment]
p.u.c will *always* lag behind Launchpad, which is where everything is published first. Since it's been less than 24 hours, I wouldn't expect it to be on p.u.c. Here's the source of truth: https://launchpad.net/ubuntu/+source/bismuth.

However, linking to the package for direct download is never the way if it's part of an official repo. In 22.04, a simple "sudo apt install kwin-bismuth" will do the trick.
