### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by spaceguybob** [Bismuth-Forge/bismuth#301]
### Summary

void linux xbps port

### A clear and concise description of what you want to happen

i would like for the bismuth application to have binaries compiled for the independant popular distro called void linux using the very nice xbps package manager

### A clear and concise description of any alternative solutions or features you've considered.

port to xbps

**Comment by b1scu1t** [comment]
Hmm...this isn't a bug for upstream (here). It is up to distro maintainers to package and publish software to their repos. The build instructions are easy to follow and Void's packages are very easy to make (like Arch's PKBUILD templates). Maybe you can ask a (KDE) Void Package Maintainer to help, they are generally quite friendly.

**Comment by gikari** [comment]
Packaging for different distribution is out of scope for the project. You can ask someone in the community to do the port.
