### ISSUE TITLE
[FEATURE]: Local installation

### ISSUE THREAD

**Issue by ilkerhk** [Bismuth-Forge/bismuth#305]
### Summary

Allow a way to install locally (without root password).

### A clear and concise description of what you want to happen

Cannot install locally.  

### A clear and concise description of any alternative solutions or features you've considered.

A local installation target can be given to the install script.

**Comment by b1scu1t** [comment]
When you say 'local' installation, do you mean having Bismuth install to the home directory of the current user (`/home/$USER/.local/share/...`)? Similar to what Plasma does when you install an extension or theme, right? If Bismuth remained as ONLY a KWin script, then yes it would be possible. But now the project also uses KCMs in System Settings to configure tiling. I'm not sure if KDE System Settings can read home directories to load KCM libraries too. 

I saw this in the docs, but I haven't tried it myself. https://develop.kde.org/docs/extend/kcm/#run-it

**Comment by ilkerhk** [comment]
Yes, that is exactly what I meant. Actually, I had already tried with -DCMAKE_INSTALL_PREFIX=~/.local    but I couldn't make it work. The link you sent uses prefix ".local/kde".  I'm not sure if it makes any difference.

**Comment by gikari** [comment]
Why do you want to install Bismuth locally?

**Comment by ilkerhk** [comment]
Because I don't need root user in order to install home folder. 
The current install script requires root password.

**Comment by gikari** [comment]
Bismuth is meant to be installed as a system package, but you can change the installation prefix using [CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html).
