### ISSUE TITLE
[Fesautre]; Launch some windows as floating always. 

### ISSUE THREAD

**Issue by srahman53171618** [Bismuth-Forge/bismuth#307]
Not sure if this is already a feature that I am just missing, but some applications tile horribly. This is not due to Bismuth but rather due to the nature of the application itself. Some examples woutld be QJackCtl, Onscreen keyboards such as onboard, and even the KDE settings app itself.  An option to add certain apps to a list that would always launch as floating would be appreciated.

**Comment by ishaanbhimwal** [comment]
This is already possible in bismuth. Go to Window tiling > Behavior > General > Window rules and add the window class in "Float Windows".

**Comment by srahman53171618** [comment]
Thank you so much. I saw that option before but I didn't quite understand what that was for. Closing issue. Thanks once again.
