### ISSUE TITLE
[FEATURE]: Sort elements in task manager according to order in bismuth

### ISSUE THREAD

**Issue by robert-elles** [Bismuth-Forge/bismuth#310]
### Summary

Sort elements in the task manager panel widget according to the order in bismuth

### A clear and concise description of what you want to happen

Hi,
let's say I am in the monocle layout. Then I can see the other open applications on the desktop by the task manager widget in the panel. See the screenshot for reference. Now in the monocle layout I want to cycle through the open windows by going left or right using the keyboard shortcuts but unfortunately the order of the windows in the task manager widget is not the same as the order of windows in bismuth. 
It would be extremely helpful if bismuth fixes the order of the windows in the task manager according to the order of windows in the tiling manager.
 
![Screenshot_20220304_093721](https://user-images.githubusercontent.com/4633229/156688503-ed855817-d048-43ea-be17-8cea71df3f37.png)

**Comment by verahawk** [comment]
There is nothing we can do. Please open a feature request on <https://bugs.kde.org> (product: plasmashell, component: task manager applet). What you want is ordering based on X an Y coordinates of windows.
