### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by badarotti** [Bismuth-Forge/bismuth#311]
### Summary

Provided package does not install on openSUSE Leap. 15.4

### Steps to Reproduce

Sudo zypper in kwin-script-tiling-bismuth-2.3.0-lp154.8.1.x86_64.rpm 

### Expected behavior

Expected to installm but it doesn't complaining about needing "libQt5Core.so.5(Qt_5.15)(64bit)". Only version 5.12 is available in Leap

### Screenshots

sudo zypper in kwin-script-tiling-bismuth-2.3.0-lp154.8.1.x86_64.rpm 
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'libQt5Core.so.5(Qt_5.15)(64bit)' needed by the to be installed kwin-script-tiling-bismuth-2.3.0-lp154.8.1.x86_64
 Solution 1: do not install kwin-script-tiling-bismuth-2.3.0-lp154.8.1.x86_64
 Solution 2: break kwin-script-tiling-bismuth-2.3.0-lp154.8.1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): 1
Resolving dependencies...
Resolving package dependencies...
Nothing to do.

### Bismuth version

2.3

### KDE Plasma version

5.18.6

### The platform KWin is running on

X11

**Comment by verahawk** [comment]
We don't provide any installation packages. Please contact the package maintainer instead.

**Comment by yorunning** [comment]
> We don't provide any installation packages. Please contact the package maintainer instead.

When will 3.0 be released? I found that the branch of 3.0 has been released. Has it not been merged into the master.

**Comment by verahawk** [comment]
> When will 3.0 be released? I found that the branch of 3.0 has been released. Has it not been merged into the master.

These `release-vX.Y.Z` branches are auto-generated by CI based on already merged commits.

@gikari wants to port the codebase to C++ before releasing new major version, so it might take a while.

**Comment by b1scu1t** [comment]
This package is for Tumbleweed, which uses the latest Qt5 LTS release (with KDE patchset). If you want to use that in Leap, you must have the Qt5 and KDE repos enabled. Check here: https://en.opensuse.org/SDB:KDE_repositories#Adding_these_repos_to_an_existing_installation

Please note that Leap 15.4 is a ***beta*** release, and not all KDE repos are available for it yet. I use these with 15.3 myself.

**Comment by gikari** [comment]
Open SUSE Leap has the packages, that are too old. Support for old systems are not planned, but current requirements in terms of versions won't be raised unless necessary, so you can wait for a new release.
