### ISSUE TITLE
[Bug]: sends kwin crashing on 5.23.5

### ISSUE THREAD

**Issue by robert-elles** [Bismuth-Forge/bismuth#312]
### Summary

I am using nixos and with the recent update to kwin 5.23.5 bismuth and kwin don't seem to get along anymore. After login from sddm kwin keeps crashing. After disabling bismuth it is working fine again.

Happens both in x11 and wayland

### Steps to Reproduce

Install bismuth in plasma/kwin 5.23.5

### Expected behavior

Works fine

### Bismuth version

2.3.0

### KDE Plasma version

5.23.5

### The platform KWin is running on

X11

**Comment by gikari** [comment]
Since I cannot reproduce the issue, please provide the crash backtrace for the KWin. You can read about how to do it [here](https://community.kde.org/Guidelines_and_HOWTOs/Debugging/How_to_create_useful_crash_reports).
