### ISSUE TITLE
[FEATURE]: disable window drop shadows

### ISSUE THREAD

**Issue by abenz1267** [Bismuth-Forge/bismuth#321]
### Summary

Currently the windows drop a shadow WHEN CLICKED. Not when focused. Also f.e. a panel would drop a shadow. 

Being able to remove those shadows would be kinda neat, as it's behaviour is rather inconsistent (focus windows vs. clicking window) and shadows might look weird to people when not using gaps.

### A clear and concise description of what you want to happen

A config option to remove drop shadows from: windows and panel.

**Comment by gikari** [comment]
Bismuth cannot modify the existing window decorations properties, and neither can it interfere with the Plasma panel.
To request such features, please fill in the request at https://bugs.kde.org.

However, in Bismuth 3.0 there is a new optional window decoration, that currently draws only colorful border without shadows. You can find it in the System Setting > Appearance > Window Decorations > Bismuth.
