### ISSUE TITLE
[Bug]: New window decoration + color scheme change = Kwin crash

### ISSUE THREAD

**Issue by Casul51** [Bismuth-Forge/bismuth#332]
### Summary

https://github.com/luisbocanegra/kde-material-you-colors/issues/8#issuecomment-1085978484

> 
> After installing Bismuth and enabling the [recently added](https://www.github.com/Bismuth-Forge/bismuth/commit/517281e1587692d70cf0093c9901d192cd776f1d) window decoration, can reproduce it (X11 too).
> The problem seems to be with changing color schemes when org.kde.bismuth.decoration is enabled, you can make it crash even without using [kde-material-you-colors](https://github.com/luisbocanegra/kde-material-you-colors) by switching between the default Breeze color schemes every 5 seconds with the following:
> 
> ```
>  #Change between BreezeDark and BreezeLight every 5 seconds
> while true; do /usr/bin/plasma-apply-colorscheme BreezeDark; sleep 5s; /usr/bin/plasma-apply-colorscheme BreezeLight; sleep 5s; done
> ```
> 
> Changing the color scheme in System Settings can also cause the crash.
> 
> So this seems to be an error in bismuth window decorations,

### Steps to Reproduce

1. Enable 'Bismuth' window decoration
2.` while true; do /usr/bin/plasma-apply-colorscheme BreezeDark; sleep 5s; /usr/bin/plasma-apply-colorscheme BreezeLight; sleep 5s; done`

### Expected behavior

Don't crash my Kwin. '^'

### Bismuth version

3.0.0

### KDE Plasma version

5.24.4

### The platform KWin is running on

Wayland

### Additional context

Just check this issue https://github.com/luisbocanegra/kde-material-you-colors/issues/8

**Comment by gikari** [comment]
Could you please test whether the linked Pull Request fixes your issue? For me, it does.
