### ISSUE TITLE
[Bug]: Update to 3.0.0 breaks keyboard shortcuts

### ISSUE THREAD

**Issue by aitorpazos** [Bismuth-Forge/bismuth#336]
### Summary

My bismuth keyboard shortcuts stopped working after upgrade to 3.0.0.

Reverting back to 2.3.0 fixed them, however I had to move them back to the kwin shortcuts category.

### Steps to Reproduce

1. Have custom shortcuts configured for bismuth
2. Install kwin-bismuth 3.0.0
3. Shortcuts stopped working

### Expected behavior

Shortcuts are migrated to `bismuth` category but they keep working as before.

### Bismuth version

3.0.0

### KDE Plasma version

5.24.4

### The platform KWin is running on

X11

### Additional context

I tried removing the old shortcuts from `.config/kglobalshortcutsrc` and doing `kquitapp5 kglobalaccel && sleep 2s && kglobalaccel5 &` but didn't work.

I then installed 2.3.0 and it started working again: `apt install kwin-bismuth=2.3.0-1`

```
Operating System: KDE neon 5.24
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.13.0-39-generic (64-bit)
Graphics Platform: X11
Processors: 4 × Unknown Type, 4 × 11th Gen Intel® Core™ i7-1185G7 @ 3.00GHz
Memory: 31.1 GiB of RAM
Graphics Processor: Mesa Intel® Xe Graphics
```

**Comment by ed-bog** [comment]
Same issue here, 
I'm on kde 5.22.5
