### ISSUE TITLE
[Bug]: The icon does not appear in the systemtray.

### ISSUE THREAD

**Issue by jardel20** [Bismuth-Forge/bismuth#347]
### Summary

After successful installation, the icon does not appear in the system tray and there is no option to enable it. How can i solve this?

### Steps to Reproduce

1. install it
(I don't know how it can be reproduced as I installed it correctly as suggested by the source code installation manual)

### Expected behavior

The icon would appear automatically without intervention.

### Bismuth version

 bismuth v3.1.1

### KDE Plasma version

plasma 5.24.4

### The platform KWin is running on

X11

### Additional context

 I'm using OpenSuse Tumbleweed.

**Comment by gikari** [comment]
The icon was deleted in 3.0, because it caused problems on some configurations. It was using an unstable experimental Qt API.

So, this is intended.

**Comment by jardel20** [comment]
Thanks
