### ISSUE TITLE
Keyboard shortcuts keep disappearing after updates

### ISSUE THREAD

**Issue by AnilRedshift** [Bismuth-Forge/bismuth#348]
I know there has been some back & forth about the keyboard settings, but I haven't seen my particular complaint which is:
After at least the last two updates (currently on `kwin-bismuth-3.1.1-1`), I lose all keyboard shortcuts.

When I go to settings -> shortcuts -> Window Tiling, every option says "No active shortcuts"
I have to go in there and re-enable all of the default settings in order to get them back working.

Let me know if there's any information I can gather to help identify the issue
```
uname -a                                                                                                                                                                                                     
Linux framebook 5.17.1-3-MANJARO #1 SMP PREEMPT Thu Mar 31 12:27:24 UTC 2022 x86_64 GNU/Linux```

**Comment by gikari** [comment]
3.1.0 had a bug in the shortcuts migration script, that broke the shortcuts. In 3.1.1 it was fixed. However, you have to renable your shortcuts manually. Sorry for the inconvenience.

**Comment by polirritmico** [comment]
Update from 2.8 to 3.1.1 and Bismuth mess my KWin shortcuts. Luckly I have backups, but IMHO should be a warning on the release so people make a "shortcut backup" just in case before the update.

Anyway, thanks for sharing your work. This plugin takes kde to the next level.
-------------------------------------------
Operating System: Gentoo Linux
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.3
Kernel Version: 5.15.32-gentoo-r1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7 CPU 870 @ 2.93GHz
Memory: 7.8 GiB of RAM
Graphics Processor: AMD JUNIPER
