### ISSUE TITLE
[FEATURE]: Option to disallow merging side areas with main area

### ISSUE THREAD

**Issue by karmux** [Bismuth-Forge/bismuth#354]
### Summary

Option to disallow merging side areas with main area when number of open windows is equal to the number of main areas.

### A clear and concise description of what you want to happen

I'm using a super ultrawide monitor (5120x1440) with a three column layout. I have a browser in the middle and other windows on the sides. Now when I close these other windows then browser takes 100% of the screen width (main area basically merges with side areas). Would be great to somehow avoid main area being merged with side areas when there are no other open windows.

Desired result:
`| empty area | browser window | empty area |`

Current result:
`| a very wide browser window |`

In case window in main area is closed then some other window would take its position (as it is already).

### Additional info

That feature would apply to layouts that has main area(s) (tile, three column, spiral, #121). For other layouts there are #232.

**Comment by benemorius** [comment]
You can use the `restrict window width` setting to accomplish something similar to that. By default it constrains the width of a window to a maximum of 1.6 times the height of the window, but it's adjustable.
