### ISSUE TITLE
[FEATURE]: Prevent window maximation

### ISSUE THREAD

**Issue by AngryAnt** [Bismuth-Forge/bismuth#355]
### Summary

In my setup I prefer to work only with un-maximized windows, regardless of active layout. There is not a scenario where a maximized window would be ideal for me. Unfortunately my Plasma install likes to maximize windows on launch seemingly whatever I do (note that `Window Management -> Window Behaviour -> Advanced -> Window placement` _is_ set to "Centered" - not "Maximized"). So one of the most used shortcuts on my system is the "toggle maximized" one as I am constantly un-maximizing windows.

A window taking up all of the screen, but with full border & decorations, is great - I just don't want the unbordered maximized state ever.

### A clear and concise description of what you want to happen

In the `Window Management -> Window Tiling -> Behaviour` settings, just below the `Prevent window minimization` toggle in the `Restrictions` section, I would like to see a similar toggle labeled `Prevent window maximation` which if checked would never allow a window to be maximized while Bismuth is running.

### A clear and concise description of any alternative solutions or features you've considered.

The window rules in the below screenshot work absolutely wonderfully to achieve my goal - right up until the point I run Bismuth which then just horribly breaks with windows getting ejected from the layouts left & right when these rules are active:

![Screenshot_2022-05-03_13-05](https://user-images.githubusercontent.com/102513/166443429-59563cff-bf53-437d-965b-909ba658a583.png)

**Comment by adrianinsaval** [comment]
Can't you make a window rule applied to all windows to set them to never maximize? Also try this: https://snapcraft.io/docs/qt5-kde-applications
If you want maximized windows but with borders and no gaps in bismuth check this: aeba8d2f3

**Comment by AngryAnt** [comment]
Whoa! Thank you for pinging this thread. Not sure if it was the recent update of Bismuth or Plasma which did it, but my above window rule now works without layout breakage!
