### ISSUE TITLE
[Bug]: Ubuntu install fails - package not found

### ISSUE THREAD

**Issue by drone1** [Bismuth-Forge/bismuth#356]
### Summary

Kubuntu 21.10 x86_64 
DE: Plasma 5.22.5 

[I first ran ``sudo apt-get update`` first.]

```➜  ~ sudo apt install bismuth

[sudo] password for ____: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package bismuth```

### Steps to Reproduce

1. Open terminal
2. Type sudo apt-get update && sudo apt install bismuth

### Expected behavior

Should install. Fails instead.

### Screenshots

_No response_

### Bismuth version

n/a

### KDE Plasma version

5.22.5

### The platform KWin is running on

X11

### Additional context

_No response_

**Comment by FaruNL** [comment]
Seems like the package is called `kwin-bismuth` for some reason

- Launchpad
  ![image](https://user-images.githubusercontent.com/34426099/167407017-d731aa8b-3bb9-420d-b159-21cb31cdd961.png)
- Terminal
  ![image](https://user-images.githubusercontent.com/34426099/167407190-745027ea-c909-47bc-ba13-50e74121f783.png)|
