### ISSUE TITLE
[Bug]: move window to next screen doesn't work with certain programs. (Strange interaction with kwin)

### ISSUE THREAD

**Issue by DashieTM** [Bismuth-Forge/bismuth#360]
### Summary

If you are running multiple screens and use the kwin move window to next screen command, then you will encounter problems with programs which are either: vertically and/or horizontally maximized | are set to dialog-window

In this case you can't move these windows to the next screen.
Luckily there is a workaround by forcing the window to not be maximized in either direction by default and marking the window as a normal-window.
There is no change in usability or behavior otherwise as far as I know, changed this on multiple programs.

I am unsure whether this is a kwin issue or a bismuth issue. 

### Steps to Reproduce

Start firefox, try to move it with the kwin move to next screen shortcut
![image](https://user-images.githubusercontent.com/72016555/168148318-41edf237-c093-4469-b27a-1befe118bd27.png)

### Expected behavior

Window moves to next screen.

Actual behavior: Window stops mid animation.

Solution: follow steps below

### Screenshots

Solution:
Alt+F3 for application settings: 
![image](https://user-images.githubusercontent.com/72016555/168145574-97c93711-bfe3-47ad-ba8a-a155b3eef07c.png)
![image](https://user-images.githubusercontent.com/72016555/168146364-4ce78f35-ea92-4775-a3fb-c2745a6ff83a.png)

### Bismuth version

3.1.1

### KDE Plasma version

5.24.5

### The platform KWin is running on

X11

**Comment by DashieTM** [comment]
oops, duplicate of https://github.com/Bismuth-Forge/bismuth/issues/218
sorry

**Comment by BearOutThere** [comment]
@DashieTM     The solution to force maximization to no doesn't work.

**Comment by DashieTM** [comment]
@KirilOkun 
I am no longer using bismuth as of now, which means I can't really see if there is something that would work. 
However the author has a few potential things that you can try out on the wikipage:
https://github.com/Bismuth-Forge/bismuth/blob/master/docs/TWEAKS.md

Also are you by chance on wayland? 
I know of a problem on wayland where the minim and maximum sizes are not properly respected by kwin, especially if you try to go below the default minimum size for applications such as the settings page.

**Comment by BearOutThere** [comment]
@DashieTM    I'm on Kubuntu x11 session.   
Krohnkite worked like a charm.    

What are you using now?

**Comment by DashieTM** [comment]
I personally use Hyprland now, but this ofc is a complete switch and had nothing to do with the quality of either kde or bismuth.

I strongly suggest trying the other fixes from the tweaks.md, if these do not work, there might be a problem with the kde version you are using in combination with bismuth.
Perhaps a bug report is appropriate.

**Comment by BearOutThere** [comment]
I tried all of the tweaks without success.  I'm on a standard Kubuntu without any custom tweaks and Kronhkite worked fine.  So all signs point to Bismuth.  Already submitted a new bug.   Let's hope it will be really fixed this time.   If not Krohnkite is still a workable option .    Thanks.
