### ISSUE TITLE
[Bug]: Tiling is bugged on new kwin version (5.25 beta)

### ISSUE THREAD

**Issue by HanabishiRecca** [Bismuth-Forge/bismuth#363]
### Summary

On new `kwin` version (5.25 beta) windows tiling doesn't update when offscreen / not on currently visible desktop. So e.g. if a window was closed offscreen, Bismuth keeps empty space until you force tiling update in some way (open new window, close some window, change layout etc.).
I suppose devs changed behavior regarding offscreen windows layout update.

### Steps to Reproduce

Use latest plasma 5.25 beta.

### Expected behavior

Should work as on earlier versions.

### Bismuth version

3.1.1

### KDE Plasma version

5.25

### The platform KWin is running on

X11

**Comment by gikari** [comment]
Could you please add a video on how to reproduce the bug?

**Comment by HanabishiRecca** [comment]
I found a way to easily trigger the bug. Use `Window to Next Desktop` / `Window to Previous Desktop` kwin shortcuts. Desktop you moving window from not retiled and keeps empty space.

**Comment by HanabishiRecca** [comment]
Video

https://user-images.githubusercontent.com/13597663/169707879-0e76c1c0-8306-4057-8d58-6cabf08e85e1.mp4

**Comment by HanabishiRecca** [comment]
Well, Plasma 5.25 is released now and still works poorly with current Bismuth version.

**Comment by j0hannes** [comment]
Same here; whenever I rearrange something I get an overlay message "Window untitled" with the Bismuth logo and tiling is broken until I restart it via the settings menu. I know that message from previous Plasma versions and I learned that some action had led to a situation in which the tiling plugin seemed to have crashed. Previously it appeared from time to time, now it affects virtually all actions concerning the positioning of windows.

**Comment by benemorius** [comment]
I can confirm it on kwin 5.25.0. For me this commit fixes it: benemorius@b43651f223b40dace4265058d96507bf8c7b0807

Can anyone else test that?

**Comment by HanabishiRecca** [comment]
> Can anyone else test that?

Seems like it helps.

**Comment by atagen** [comment]
I found benemorius patches (tried the pr/* and master branches) fix the basic problem where no windows will obey next screen at all, but some windows (such as Firefox) will still pop themselves into a broken half-tiled state when asked to move screen. They can be reset by floating and retiling, and while floating they will change screen no problem.
