### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ErKaf** [Bismuth-Forge/bismuth#368]
### Summary

The Window Decorations don't show up.

### Steps to Reproduce

1. Go to Appearance -> Window Decorations
2. Look for the Bismuth theme
3. ?! Don't find it !?
4. !?!?

### Expected behavior

1. Go to Appearance -> Window Decorations
2. Look for the Bismuth theme
3. Find Bismuth theme
4. Profit

### Bismuth version

bismuth-2.3.0-1.fc36.x86_64

### KDE Plasma version

Plasma 5.24.5

### The platform KWin is running on

X11

**Comment by evanslify** [comment]
If you're using `copr` - this is fixed by a upcoming PR: https://github.com/JCapucho/fedora-rpms/pull/2

**Comment by gikari** [comment]
> Bismuth version
> bismuth-2.3.0-1.fc36.x86_64

Your version is old. Window decorations were introduced in 3.x. You should upgrade your installation.

**Comment by ErKaf** [comment]
> > Bismuth version
> > bismuth-2.3.0-1.fc36.x86_64
> 
> Your version is old. Window decorations were introduced in 3.x. You should upgrade your installation.

This is a fresh installation.

**Comment by ErKaf** [comment]
> If you're using `copr` - this is fixed by an upcoming PR: [JCapucho/fedora-rpms#2](https://github.com/JCapucho/fedora-rpms/pull/2)

Yes, I use copr. When will this update be there? 
And is copr always that far behind with updates?

**Comment by gikari** [comment]
> This is a fresh installation.

I mean, you should upgrade Bismuth. You won't get any window decoration if you use an old version.

**Comment by ErKaf** [comment]
> > This is a fresh installation.
> 
> I mean, you should upgrade Bismuth. You won't get any window decoration if you use an old version.

I used your link for Fedora: https://copr.fedorainfracloud.org/coprs/capucho/bismuth/
This is the latest version here.

Sorry, I'm really new to Fedora. Am I doing something wrong?

**Comment by gikari** [comment]
The version from this repository is old (2.3.0). You should ask the person in charge of this copr repo to update the bismuth version to 3.1.x. This way, you will get an update.

**Comment by ErKaf** [comment]
> copr is unofficial package repository of Fedora, anyone can provide their own .rpm spec and have it hosted there. The PR provided above is still under change/review process.

I see. So I just have to be patient for a little while longer, do I understand that correctly?

When I type sudo dnf update, the update will be there sometime in the next week or so? Or is copr updated with any other command.
