### ISSUE TITLE
[Bug]: crash in kconfigwatcher usage

### ISSUE THREAD

**Issue by davidedmundson** [Bismuth-Forge/bismuth#379]
### Summary

We had a downstream report: https://bugs.kde.org/show_bug.cgi?id=455810

Crash is caused by 

    connect(m_kdeglobalsWatcher.data(), &KConfigWatcher::configChanged, [this](const KConfigGroup &group, const QByteArrayList &names) {

we want

    connect(m_kdeglobalsWatcher.data(), &KConfigWatcher::configChanged, this, [this](const KConfigGroup &group, const QByteArrayList &names) {

the sharedptr can outlive this class, therefore it needs scoping.

### Steps to Reproduce

see above

### Expected behavior

see above

### Bismuth version

any

### KDE Plasma version

5.25.

### The platform KWin is running on

X11

**Comment by davidedmundson** [comment]
In future would you consider adding some "namespace Bismuth" everywhere. It'll save me some time upstream if we can spot 3rd parties earlier

**Comment by gikari** [comment]
> In future would you consider adding some "namespace Bismuth" everywhere. It'll save me some time upstream if we can spot 3rd parties earlier

Yeah, sure. But decoration code was already in a Bismuth namespace, wasn't if?

**Comment by davidedmundson** [comment]
> > In future would you consider adding some "namespace Bismuth" everywhere. It'll save me some time upstream if we can spot 3rd parties earlier
> 
> Yeah, sure. But the decoration code was already in a Bismuth namespace, wasn't it?

Ah maybe. Bismuth wasn't in the backtrace we had, but maybe the lambda got inlined.

**Comment by davidedmundson** [comment]
Thanks

**Comment by xpufx** [comment]
@gikari I have a similar issue but it does not need Bismuth enabled, just the Window Decoration bismuth has to be enabled. Would this fix that or is it a separate issue?

**Comment by gikari** [comment]
> @gikari I have a similar issue but it does not need Bismuth enabled, just the Window Decoration bismuth has to be enabled. Would this fix that or is it a separate issue?

Yes.

**Comment by xpufx** [comment]
> > @gikari I have a similar issue but it does not need Bismuth enabled, just the Window Decoration bismuth has to be enabled. Would this fix that or is it a separate issue?
> 
> Yes.

I applied the changes. Seems to fix it. Thanks.
