### ISSUE TITLE
[FEATURE] shortcut/option to return floating window/application to tiling

### ISSUE THREAD

**Issue by salperinlea** [Bismuth-Forge/bismuth#390]
Sometimes I need to move a single window out of tiling, e.g. to view contents that get hidden when the window is below a certain size/width. Because tiled windows ignore the floating windows when they size themselves, to get back to whatever state of affairs I had, I need to untile all my windows and then move them around myself. It would be very convenient if a window that has been moved from tiled to floating could be moved back into tiling via a shortcut, or, alternately, if tiled windows could still be moved about to halves/quarters/etc of the screen.

**Comment by krshrimali** [comment]
Hi, @salperinlea - Apologies if I didn't get you right here, but to move a tiling window to floating window - you can do Super + F and to return it back to tiling, you can again do Super + F. Does that not help your use case?

**Comment by salperinlea** [comment]
Hi @krshrimali -- as far as I can tell Super+F _is supposed to_ move all windows back/forth between floating and tiling. However, my finding is that it only does this to windows that have not been manually removed from tiling --- they will remain floating in perpetuity. If they're _meant_ to return back and forth from tiling when this shortcut is pressed, then I suppose I have a bug request, rather than a feature?
