### ISSUE TITLE
[Bug]: Can't install on Debian 11 due to dependency error

### ISSUE THREAD

**Issue by masscream** [Bismuth-Forge/bismuth#392]
### Summary

Hello, looks like non of the method posted on the Installation instructions is working. After adding the repo....

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kwin-bismuth : Depends: libstdc++6 (>= 11) but 10.2.1-6 is to be installed
E: Unable to correct problems, you have held broken packages.
```
Installed via deb file

```
sudo apt install -f
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  kwin-bismuth
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 655 kB disk space will be freed.
Do you want to continue? [Y/n] 
```
Anyway, the link is broken too for
```
https://deb.volian.org/volian/pool/main/b/bismuth/kwin-bismuth_2.2.0-1_amd64.deb
```

### Steps to Reproduce

1. Add the official repo
2. Try to install as instructed

### Expected behavior

It should install. At least there is not written that Debian 11 is not supported.

### Bismuth version

3.1.1

### KDE Plasma version

5.20.5

### The platform KWin is running on

X11

**Comment by krshrimali** [comment]
Hey @masscream and @CodedNil - I understand it's not expected that everyone can build it from source, but just curious - would you like to try building bismuth from the source? It's [fairly simple](https://github.com/Bismuth-Forge/bismuth/blob/master/CONTRIBUTING.md).

**Comment by masscream** [comment]
Oh yes, I already tried, but it's not that fairly simple. I understand that I can't request any fixes and what we do, we may do for fun and in our free time. By the time I wanted to try bismuth,  I also tried to compile the code when the easy way did not work. With the following error.

```
[13/51] 🏗️ Compiling and bundling TypeScript sources...
FAILED: src/kwinscript/bismuth/contents/code/index.mjs 
cd /media/masscream/Data/Workspace/bismuth/build/src/kwinscript && npx tsc --noEmit --incremental && npx esbuild --bundle /media/masscream/Data/Workspace/bismuth/src/kwinscript/index.ts --outfile=/media/masscream/Data/Workspace/bismuth/build/src/kwinscript/bismuth/contents/code/index.mjs --format=esm --platform=neutral

                                                                               
                This is not the tsc command you are looking for                
                                                                               

To get access to the TypeScript compiler, tsc, from the command line either:

- Use npm install typescript to first add TypeScript to your project before using npx
- Use yarn to avoid accidentally running code from un-installed packages
npm ERR! code 1
npm ERR! path /media/masscream/Data/Workspace/bismuth/build/src/kwinscript
npm ERR! command failed
npm ERR! command sh -c tsc "--noEmit" "--incremental"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/masscream/.npm/_logs/2022-07-18T08_46_16_594Z-debug.log
[18/51] Building CXX object src/kcm/CMakeFiles/kcm_bismuth.dir/bismuth.cpp.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:10: build] Error 1
```
Because I'm not a code kind of a guy, my journey just ended there, I did not find any info on the internet that would lead me, that this is system related issue (missing library I could install or so). Therefore, I just abandoned trying the project. In the meantime I found another solution how to achieve things I wanted bismuth for.... So, there is no fix necessary for me anymore. I was just letting know that  probably debian users with the latest sys version won't be able to install the project, and if they are not skillful enough to fix the error themselves, probably in the code, they won't use it, same as me.

**Comment by gikari** [comment]
> Add the official repo

There is no official repo for Bismuth. Therefore, the issues with installation should be forwarded to the repo maintainers.
