### ISSUE TITLE
[Bug]: Tiling breaks with message "Window untitled"

### ISSUE THREAD

**Issue by j0hannes** [Bismuth-Forge/bismuth#395]
### Summary

When moving a window from one screen to another (via Alt + drag&drop), the tiling functionality on the empty target screen breaks once the window is dropped. Additionally, a message "Window untitled" is shown (see screenshot).

The tiling functionality can be restored by disabling and re-enabling it in the settings.

### Steps to Reproduce

1. Open any graphical application.
2. Hold Alt.
3. Left click on the respective window and hold the mouse button.
4. Move the mouse to another screen that it empty.
5. Release the mouse button.

### Expected behavior

The window should be maximized as there is no other window for effective tiling.

### Screenshots

![Screenshot_20220711_170008](https://user-images.githubusercontent.com/3944397/178295498-ac470651-0794-48da-989a-deb6ba4caeba.png)

### Bismuth version

3.1.2

### KDE Plasma version

5.25.2

### The platform KWin is running on

X11

**Comment by ibndiaye** [comment]
Yep, Ive been getting the same thing as well when i move my windows around (META+drag&drop) since KDE 5.25.

**Comment by j0hannes** [comment]
Now that you mention it, its appearance might well have coincided with the release of 5.25 - and not be related with the bismuth version.

**Comment by ibndiaye** [comment]
Yeah probably, my temporary fix that i use now is go in your KDE settings:
Shortcuts->Window Tiling->Toggle Active Window Floating (set a hotkey)

**Comment by j0hannes** [comment]
That's great, thanks! That will do the job until the issue is fixed.

**Comment by krshrimali** [comment]
Hi, @j0hannes and @ibndiaye - Appreciate the discussion. See if this helps:

1. Go to "Windows Tiling" option in the system settings.
2. In the "Behavior" tab, disable "Untile windows by dragging" option (in "Windows" section).

Please see the screenshot:
![image](https://user-images.githubusercontent.com/19997320/179426881-35106a50-5c4e-4112-8a94-4018e8f02f8c.png)

I'm assuming that you are trying to drag a window using a mouse from one screen to another, and when this option is _enabled_, it converts it into floating mode. If you don't want this, you can disable the feature.

Please let me know if this doesn't help. :)

**Comment by ibndiaye** [comment]
Holy smokes, that actually worked. Thanks @krshrimali !

**Comment by j0hannes** [comment]
I had this option already disabled, but enabled and disabling it again seemed to have worked.
