### ISSUE TITLE
[FEATURE]: Smart Gaps

### ISSUE THREAD

**Issue by willthong** [Bismuth-Forge/bismuth#404]
### Summary

(Outer) gaps waste screen real estate when there is only one window displayed.

### A clear and concise description of what you want to happen

It would be great if we could have a feature for disabling gaps when there is only one window on the workspace. This would be similar to the implementation on [i3-gaps](https://github.com/Airblader/i3). Thanks!

**Comment by gikari** [comment]
We already have an option to "Maximize Sole Window", that does the same (as far as I understand). Is there any difference between it and your proposal?

**Comment by willthong** [comment]
Hi @gikari - it does, thank you! My apologies for having missed this - coming from a non-KDE background I'm frankly flummoxed by the wild variety of options!
