### ISSUE TITLE
Option to Activate Bismuth through command line

### ISSUE THREAD

**Issue by loremed** [Bismuth-Forge/bismuth#411]
I just transitioned from Krohnkite.
With Krohnkite you could check whether it was active or inactive with
``
kreadconfig5 --file kwinrc --group Plugins --key krohnkiteEnabled
``
and activate/deactivate it with 
`` kwriteconfig5 --file kwinrc --group Plugins --key krohnkiteEnabled true/false``

With this you could write a simple script which would activate or deactivate Krohnkite every time it was executed.
By assigning a shortcut to the script you could easily toggle the status of Krohnkite.

Is there a way to do the same thing with Bismuth?

If not, will it be added?

**Comment by gikari** [comment]
You can do the same with
```
 kreadconfig5 --file kwinrc --group Plugins --key bismuthEnabled
```
