### ISSUE TITLE
[Bug]: Some apps start with incorrect window size in 3.1.3

### ISSUE THREAD

**Issue by HanabishiRecca** [Bismuth-Forge/bismuth#421]
### Summary

After the 3.1.3 update some apps start with incorrect window size and do not tile until some control action performed.

Seems like [this line](https://github.com/Bismuth-Forge/bismuth/commit/3c6b367a3acdc7726d65b10bfc0706eec23d191a#diff-9ac952677f67f82d4ce024a474516d62cab4d4e4c14f096a0cd8890e401539e9L339) was useful. Adding it back (along with reverting https://github.com/Bismuth-Forge/bismuth/commit/a95ff95c34d8b24378a94c8088827593af7a8b55) solves the issue.

### Steps to Reproduce

Affects some apps. E.g. `kwrite` in my case.

### Expected behavior

Windows should tile properly.

### Bismuth version

3.1.3

### KDE Plasma version

5.25.4

### The platform KWin is running on

X11

**Comment by gikari** [comment]
Which applications are affected?

I cannot reproduce this behavior.

**Comment by gikari** [comment]
For me, it works like this: after launching, a maximized window snaps into layout, but still has it's maximized state. Apart from that nothing breaks.

**Comment by Mr-MD** [comment]
I'm having this same issue but for me it's affecting dolphin file manager.
![Screenshot_20220914_081324](https://user-images.githubusercontent.com/48261007/190194433-4cfec897-e1ff-4c2a-9bf1-90e64a7270c0.png)

**Comment by Mr-MD** [comment]
I was able to reproduce the issue a second computer, it seems when I change any of the window tiling settings in kde the issue comes back. I downgraded to v3.1.2 for now.

**Comment by puglet5** [comment]
@xfzv, hi! As a temporary fix, I suggest setting the following window rules:

![image](https://user-images.githubusercontent.com/80723278/196802105-3bf6492f-136a-4a9e-b674-4931e84b4a9b.png)

This fixes issues for me, though I'm not yet sure if it breaks anything. You might set this for dolphin specifically. Let me know if it works.

**Comment by yorunning** [comment]
> @xfzv, hi! As a temporary fix, I suggest setting the following window rules:
> 
> ![image](https://user-images.githubusercontent.com/80723278/196802105-3bf6492f-136a-4a9e-b674-4931e84b4a9b.png)
> 
> This fixes issues for me, though I'm not yet sure if it breaks anything. You might set this for dolphin specifically. Let me know if it works.

It affects the normal display of krunner

**Comment by yorunning** [comment]
> > It affects the normal display of krunner
> 
> Assuming the issue only affects Dolphin on your end (like me), use `Exact Match` `dolphin` for `Window class (application)` and krunner position won't be affected.

Krunner is normal now, thank you

**Comment by rayan-mazouz** [comment]
same issue here. this fixed it. The initial placement rule is unnecessary for me.

> > @xfzv, hi! As a temporary fix, I suggest setting the following window rules:
> > ![image](https://user-images.githubusercontent.com/80723278/196802105-3bf6492f-136a-4a9e-b674-4931e84b4a9b.png)
> > This fixes issues for me, though I'm not yet sure if it breaks anything. You might set this for dolphin specifically. Let me know if it works.
> 
> It affects the normal display of krunner
