### ISSUE TITLE
[DEV]: Change Gentoo source to official

### ISSUE THREAD

**Issue by viperML** [Bismuth-Forge/bismuth#433]
### Summary

A year ago I submited this PR https://github.com/Bismuth-Forge/bismuth/pull/172 so my Gentoo Overlay was in the Readme for installation.

I haven't used Gentoo for a long time now (on NixOS now), and the overlay is not updated or maintained anymore. I won't remove the repo, but I would like to remove the line from the Readme, or add something like `[deprecated]`, whatever you see fit...

**Comment by polirritmico** [comment]
There's an ebuild on the official repository: https://packages.gentoo.org/categories/kde-misc
