### ISSUE TITLE
[FEATURE]: Requesting documentation on bismuth configs for backing up

### ISSUE THREAD

**Issue by embeddedpenguin** [Bismuth-Forge/bismuth#435]
### Summary

I'm not sure where configurations are saved and modified when using the gui to configure bismuth, so I'm not sure how I can easily back up a configuration and move it to another machine.

### A clear and concise description of what you want to happen

In most other window managers, the configuration is a file or set of files. I'm assuming there's a single file bismuth uses for configuration. I just would like to know what it is and if it is easily editable in a text editor.

**Comment by polirritmico** [comment]
Maybe this will help:
```command
$ cd ~/.config
$ grep -rnwi ./* -e "bismuth"
./kconf_updaterc:5:done=bismuth-new-logger
./kconf_updaterc:10:done=bismuth-old-conf-ui
./kconf_updaterc:15:done=bismuth-shortcuts-category
./kglobalshortcutsrc:2:update_info=bismuth_shortcuts_category.upd:bismuth-shortcuts-category,bismuth_shortcuts_from_kwin.upd:bismuth-shortcuts-from-kwin
./kglobalshortcutsrc:13:[bismuth]
./kwinrc:70:[Script-bismuth]
```
So `~/.config/kwinrc` and `~/.config/kglobalshortcutsrc`
