### ISSUE TITLE
[DEV]: Who is the maintainer of the Volian repo?  Bismuth in that repo is outdated.

### ISSUE THREAD

**Issue by YamiYukiSenpai** [Bismuth-Forge/bismuth#444]
### Summary

The one in Volian repo hasn't been updated since 3.1.2, and I'd like to have it updated since 5.25 doesn't appear to let me move my windows  from my secondary 4K to primary 1440p.   Also, Kubuntu 22.10 is about to come out and the backports PPA has 5.26.

### Additional info

I didn't use the Bug report since I'm not currently sure if the latest ones will fix my issue.

**Comment by biqqles** [comment]
Using blame on the readme you can see it was added in #233 by @volitank

**Comment by volitank** [comment]
I just updated it yesterday to the latest so 3.1.4 should be available to you now. Let me know if this isn't the case.

**Comment by YamiYukiSenpai** [comment]
Thanks!

**Comment by volitank** [comment]
Glad to hear that it's working for you. Running smooth on my machine as well.

For future reference regarding who to contact for .debs, you can run `apt show kwin-bismuth` and it'll have the maintainer listed in there.

```
Maintainer: Volian Developers <volian-devel@volian.org>
```

Additionally if you have the source repositories enabled `apt-cache showsrc kwin-bismuth` gives you a little more

```
Uploaders: Blake Lee <blake@volian.org>
Vcs-Browser: https://gitlab.com/volian/bismuth
Vcs-Git: https://gitlab.com/volian/bismuth.git
```

Semi-Related: We are currently in the process of making an official Debian package for Bismuth. I'm not sure when it will hit the Sid repos, but I'm betting we can get it done before the next stable Debian release.

https://salsa.debian.org/qt-kde-team/extras/kwin-bismuth
