### ISSUE TITLE
[Bug]: Bismuth has Broken Since Updating to Plasma 5.26.

### ISSUE THREAD

**Issue by FedX-sudo** [Bismuth-Forge/bismuth#447]
### Summary

This morning I have updated to Plasma 5.26 from Plasma 5.25, and Bismuth has created an issue where windows will not appear on my desktop. I am unsure what is causing this issue, but it appears that the APIs have changed since the change to 5.26. 

Note, I am using NixOS Unstable, I doubt this is a Nix issue, but it's certainly worth mentioning. 

### Steps to Reproduce

1. Update to Plasma 5.26
2. Now windows will not appear if Bismuth is enabled. 

### Expected behavior

Windows work as expected. 

### Bismuth version

3.1.3

### KDE Plasma version

5.26.1

### The platform KWin is running on

Wayland

**Comment by ChrisCochrun** [comment]
I have the same issue. Also, on NixOS unstable. Maybe it's due to NixOS more than bismuth itself?

**Comment by FedX-sudo** [comment]
Potentialy, but it also could be the fact that NixOS is shipping Plasma 5.26 before just about anything else.

**Comment by CarlosEkisde** [comment]
Upgrade to Bismuth 3.1.4 , explicitly released to make Bismuth compatible with Kwin 5.26 :P 

If NixOS has shipped Plasma 5.26 without upgrading Bismuth the fault is on their side.

**Comment by ChrisCochrun** [comment]
Ohhhh. It appears that NixOS is still using bismuth 3.1.3. They did not update. Guess we shall see if that can get changed.

**Comment by FedX-sudo** [comment]
Ah, that makes more sense. Thanks for catching that!
