### ISSUE TITLE
[Bug]: Bismuth sets all windows to 0x0 and tilies them off of screen on left hand side.

### ISSUE THREAD

**Issue by Duser919** [Bismuth-Forge/bismuth#451]
### Summary

Enabling Bismuth tiling sends all windows to the left of the display and resizes all windows to 0x0 (for all windows that do not have a minimum size). 0x0 windows do not expand after disabling tiling. Behavior happens immediately after enabling tiling, bug persists after restart. 

Settings can be dragged back into the main screen through the right click menu on the task bar to disable tiling. 0x0 windows can also be resized back through the same menu (right click on taskbar icon -> more -> resize/move). 

### Steps to Reproduce

1- Enable Bismuth tiling through window management -> windows tiling

### Expected behavior

Tiling windows remain on main screen and are not resized to 0x0

### Bismuth version

3.1.3

### KDE Plasma version

5.26.2 

### The platform KWin is running on

Wayland

### Additional context

Running on Fedora 37 release.
This is probably the first bug report i filed. Let me know if i can provide better logs.

**Comment by Rossub** [comment]
Same problem in x11 too. I'm also using fedora 37.

**Comment by forlornidealist** [comment]
I'm also having this issue in both Wayland and x11 after upgrading to Fedora 37

**Comment by 4c3e** [comment]
also having this issue on f37 + kde 5.26 wayland

**Comment by 4c3e** [comment]
Okay it seems that fedora 37 is using Bismuth 3.1.3 which doesn't have the fix for plasma 5.26. It looks like [bismuth 3.1.4](https://github.com/Bismuth-Forge/bismuth/releases/tag/v3.1.4) includes a fix for 5.26, so upgrading likely fixes the issue.

**Comment by eclipseo** [comment]
It bothers me too, I'm gonna push it to Fedora 37.

**Comment by Duser919** [comment]
Thanks Eclipseo! Looking forward to seeing this in Fedora 37.

Since this issue is already fixed in the new version, I'm closing this thread.

**Comment by ekinmeroglu** [comment]
Thanks @eclipseo for the 3.1.4 package on fc37, works like a charm. Meanwhile Plasma 5.26 has landed on fc36, and as expected bismuth is experiencing the same problem on that version now. Any chance of getting 3.1.4 to fc36 repos too?
