### ISSUE TITLE
[Bug]: Outdated installation instructions for OpenSUSE - MR is available but hasn't been merged

### ISSUE THREAD

**Issue by phrxmd** [Bismuth-Forge/bismuth#461]
### Summary

The installation instructions for OpenSUSE in README.md refer to an outdated repository. A fix is available in MR #446 but hasn't been merged.

### Steps to Reproduce

1. Try to install Bismuth on OpenSUSE following the install instructions
2. Failure, because Bismuth is now in an official repository, no longer in the user repository mentioned in README.md

### Expected behavior

The documentation should be updated. MR #446 contains a simple fix to make README.md point to the correct repo has been out for two months; is there something fundamental that blocks it from merging? 

### Bismuth version

3.1.4

### KDE Plasma version

5.26.4

### The platform KWin is running on

Wayland

**Comment by gikari** [comment]
Thanks for the PR, sorry for making you wait (merged #446). Due to my origins, I recently changed the country of living and my lifestyle. Because of that, now I am not able to properly maintain the extension, apart from simple PRs like yours. Thank you for understanding.
