### ISSUE TITLE
Steam Deck Support

### ISSUE THREAD

**Issue by jacobranson** [Bismuth-Forge/bismuth#462]
Hello! I was curious what the install process looks like for the Steam Deck (if that is supported). Cannot build from source, nor use the distribution packages with the locked root filesystem. Is there a rootless way to install? Can I just grab the tar file from Releases and install it somewhere? Thanks!

**Comment by gikari** [comment]
Hello, there is SteamDeck support for the reason, that the root file system is read-only. This would not be an issue, if KDE extensions could be packaged as Flatpak (like the apps you can install on SteamDeck), but it is not possible currently.
