### ISSUE TITLE
[Bug]: Windows don't show up

### ISSUE THREAD

**Issue by ArtyomSavostin** [Bismuth-Forge/bismuth#465]
### Summary

On Fedora KDE spin, after installing bismuth and turning on tiling all windows stoped showing up. I can still interact with them, but they are somewhere off the screen. KRunner, application launcher and context menus still worked fine.

### Steps to Reproduce

Install bismuth on Fedora KDE spin
Turn on tiling
Open some windows

### Expected behavior

Windows should show up.

### Bismuth version

3.1.3-1.fc36

### KDE Plasma version

5.26.4

### The platform KWin is running on

X11

**Comment by Nano-Ocelot** [comment]
Updating to release version 3.1.4 or git master should fix this bug for you. Version 3.1.3 doesn't support Plasma ≥ 5.26
