### ISSUE TITLE
[Bug]: System Tray options Scaling to fullscreen

### ISSUE THREAD

**Issue by harukayamazaki** [Bismuth-Forge/bismuth#470]

**Comment by b1scu1t** [comment]
Are you sure this is on X11? Those dialogs should be whitelisted by default. I can't reproduce this problem.

**Comment by eight85** [comment]
> Are you sure this is on X11? Those dialogs should be whitelisted by default. I can't reproduce this problem.

Yes I run x11, wayland is not usable in my current setup. You might be on a more updated version of bismuth, the ubuntu builds are outdated. I'm also not on a LTS release so thats more to factor in I suppose. Im closing this issue regardless as bismuth's development will be discontinued when 5.27 releases.
