### ISSUE TITLE
[Bug]: Bismuth tile management panel is missing from Window Management settings on Neon

### ISSUE THREAD

**Issue by BearOutThere** [Bismuth-Forge/bismuth#503]
### Summary

After upgrading Neon to Plasma 6 i installed kwin-bismuth but  after a successful install 'Window Tiling' panel is not availble in Window Management settings.

### Steps to Reproduce

1.  Ran apt update
2. Installed apt install kwin-bismuth
3. Restarted computer
4. Opened Windows Management settings
5. Bismuth "Windows Tiling"  is missing

I tried both the official Ubuntu repo as well as Volian.  Same result.  Installation goes through without any errors but Window Tiling is missing from Window Management

### Expected behavior

Window Tiling should be available

### Bismuth version

2.3.0

### KDE Plasma version

6

### The platform KWin is running on

Wayland

**Comment by omegaatt36** [comment]
I have the same question, thanks for your report :)

**Comment by BearOutThere** [comment]
After noticing that Bismuth has not been updated for over 2 years i looked for other window tiling options and found that Plasma has a built in tiling functionality.   Here's an article describing it. 

Since it seems that Bismuth is following Krohnkite into the unmaintained oblivion I'll close this bug .

https://www.tuxedocomputers.com/en/Smart-windows-Tiling-with-KDE-Plasma-5-27.tuxedo
