### ISSUE TITLE
[Bug]: Krohnkite importing script doesn't actually work

### ISSUE THREAD

**Issue by gianmarcogg03** [Bismuth-Forge/bismuth#90]
### Summary

The script to import the keybindings from Krohnkite doesn't actually work.

### Steps to Reproduce

1. Run the importing script
2. Enable Bismuth

### Expected behavior

The keybindings should be the same as the ones I had on Krohnkite.

### Bismuth version

1.0.1

### KDE Plasma version

5.22.5

### The platform KWin is running on

X11

### Additional context

Little question: does it also import the settings?

**Comment by gikari** [comment]
> Little question: does it also import the settings?

No, it does not import the settings. Only keybindings.



> The keybindings should be the same as the ones I had on Krohnkite.

What's your contents of the `~/.config/kglobalshortcutsrc`? Did you reload the script?

**Comment by gianmarcogg03** [comment]
https://pastebin.com/qbptXJJ0

What do you mean exactly by "reload the script"?

**Comment by gikari** [comment]
> What do you mean exactly by "reload the script"?

https://github.com/gikari/bismuth/blob/master/TWEAKS.md#making-changes-to-configuration

**Comment by gikari** [comment]
I see it in the paste data, that some shortcuts have been imported, but some are not. One of which is Tile Layout (I made a typo in the script, it's an easy fix) and one is the toggle floating layout, which is expected, and you need to rebind it manually, because Bismuth only has Toggle Floating Layout action and no Float Action. The key is brought only from Float All action, which is bound by default.

**Comment by gianmarcogg03** [comment]
> > What do you mean exactly by "reload the script"?
> 
> https://github.com/gikari/bismuth/blob/master/TWEAKS.md#making-changes-to-configuration

Doesn't this apply only to the settings and not the keybindings?

**Comment by gikari** [comment]
> > > What do you mean exactly by "reload the script"?
> > 
> > 
> > https://github.com/gikari/bismuth/blob/master/TWEAKS.md#making-changes-to-configuration
> 
> Doesn't this apply only to the settings and not the keybindings?

Sorry, I missed that you have Bismuth disabled during the script run. It is not necessary. What was your output of the script, when you run it?

**Comment by gianmarcogg03** [comment]
```
Config file path: ~/.config/kglobalshortcutsrc
Importing Krohnkite shortcuts...
```
That's it. No errors or anything...

**Comment by gikari** [comment]
What will happen if you open Shortcuts Module in the System Settings? Are correct shortcuts displayed for Bismuth entries? From the resulting file, I see, that shortcuts config was changed.

**Comment by gianmarcogg03** [comment]
https://user-images.githubusercontent.com/28053717/135772757-0e17d624-4510-46e4-9a40-41120471a439.mp4

**Comment by gikari** [comment]
So, is it correct, that your `kglobalshortcutsrc` contains the correct Bismuth Keybindings, but the Shortcuts module do not show them, instead showing the old configuration? Will this help:
```
systemctl --user restart plasma-kglobalaccel.service
```
?

**Comment by gianmarcogg03** [comment]
![2021-10-04_20-01](https://user-images.githubusercontent.com/28053717/135901169-2eb439b9-5ae9-410f-8bcc-8c6db5448045.png)

**Comment by gikari** [comment]
So, reloading global shortcuts service didn't help? Maybe logging in and out will help?

**Comment by xeruf** [comment]
Same issue. I suspect it might be related to conflicts in keyboard configuration - if I try to manually migrate, it asks me to remove the binding for Krohnkite, which I do not really want so I keep the option to migrate back just in case.

**Comment by verahawk** [comment]
> which I do not really want as I want the option to switch back just in case.

FYI you can use the "Export Scheme" button to back up your shortcuts.
